export class OrderSaveModel 
                {
                 public Id: number ;
 public ApplicationSource_Id: number;
 public TrackingNumber: number;
 public ApplicationType_Id: number;
 public IsSigned: boolean;
 public SignededAppAttachement_Id: number;
 public RemarksTime: Date;
 public Status_Id: number;
 public StatusByOfficer_Id: number;
 public StatusByOfficerName: string ;
 public StatusTime: Date;
 public ForwardingOfficer_Id: number;
 public FromOfficer_Id: number;
 public FromOfficerName: string ;
 public ForwardTime: Date;
 public PandSOfficer_Id: number;
 public PandSOfficerName: string ;
 public IsPending: boolean;
 public RecieveTime: Date;
 public FileRequested: boolean;
 public FileRequest_Id: number;
 public IsPersonAppeared: boolean;
 public PersonAppeared_Id: number;
 public RawText: string ;
 public FromDate: Date;
 public ToDate: Date;
 public TotalDays: number;
 public LeaveType_Id: number;
 public CurrentScale: number;
 public RetirementType_Id: number;
 public FromHF_Id: number;
 public ToHFCode: string ;
 public ToHF_Id: number;
 public FromDept_Id: number;
 public ToDept_Id: number;
 public FromDesignation_Id: number;
 public ToDesignation_Id: number;
 public ToScale: number;
 public SeniorityNumber: string ;
 public AdhocExpireDate: Date;
 public ComplaintType_id: number;
 public DispatchNumber: string ;
 public DispatchDated: Date;
 public DispatchFrom: string ;
 public DispatchSubject: string ;
 public Remarks: string ;
 public EmployeeName: string ;
 public FatherName: string ;
 public CNIC: string ;
 public DateOfBirth: Date;
 public Gender: string ;
 public Department_Id: number;
 public Designation_Id: number;
 public HealthFacility_Id: number;
 public HfmisCode: string ;
 public FileNumber: string ;
 public MobileNo: string ;
 public EMaiL: string ;
 public JoiningGradeBPS: number;
 public CurrentGradeBPS: number;
 public EmpMode_Id: number;
 public EmpStatus_Id: number;
 public Created_Date: Date;
 public Created_By: string ;
 public Users_Id: string ;
 public IsActive: boolean;
 public Profile_Id: number;
 public ForwardingOfficerName: string ;
 public OrderDate: Date;
 public CurrentLog_Id: number;
 public FileRequestTime: Date;
 public FileRequestStatus: string ;
 public FileRequestStatus_Id: number;
 public FileUpdated_Id: number;
 public DDS_Id: number;
 public AppointmentEffect: boolean;
 public AppointmentDate: Date; 
                }


                export class LeaveOrderView {
                    public Id: number;
                    public Profile_Id:  number;
                    public LeaveType_Id:  number;
                    public FromDate:  Date;
                    public ToDate:  Date;
                    public TotalDays:  number;
                    public FileNumber: string;
                    public OrderDate:  Date;
                    public SignedBy: string;
                    public Officer_Id:  number;
                    public Application_Id:  number;
                    public OrderHTML: string;
                    public EntityLifecycle_Id:  number;
                    public ESRId: number;
                    public ProfileId:  number;
                    public EmployeeName: string;
                    public CNIC: string;
                    public Designation: string;
                    public HealthFacility: string;
                    public WorkingHealthFacility: string;
                    public Scale:  number;
                    public Contact: string;
                    public OfficerName: string;
                    public TransferTypeID:  number;
                    public OrderType: string;
                    public LeaveTypeName: string;
                    public DistrictName: string;
                    public DateTime:  Date;
                    public UserName: string;
                    public Last_Modified_By: string;
                    public UserId: string;
                    public IsActive: boolean;
                }