
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AAA_SCRIPT_TRANSER_HF
{

    public string FullName { get; set; }

    public string TehsilName { get; set; }

    public string HFTypeName { get; set; }

}

}
