
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AdhocInterviewBatch
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AdhocInterviewBatch()
    {

        this.AdhocInterviewBatchApplications = new HashSet<AdhocInterviewBatchApplication>();

    }


    public int Id { get; set; }

    public Nullable<int> Interview_Id { get; set; }

    public string BatchNo { get; set; }

    public Nullable<int> Candidates { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

    public string Venue { get; set; }

    public Nullable<int> VenueHF_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }



    public virtual AdhocInterview AdhocInterview { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AdhocInterviewBatchApplication> AdhocInterviewBatchApplications { get; set; }

}

}
