
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AdhocSelectedMerit
{

    public int Id { get; set; }

    public Nullable<int> Application_Id { get; set; }

    public string DistrictName { get; set; }

    public Nullable<int> MeritNumber { get; set; }

    public Nullable<int> Vacancy { get; set; }

    public string Selected { get; set; }

    public Nullable<bool> IsSelected { get; set; }

    public Nullable<int> Phase { get; set; }

    public Nullable<int> BatchNo { get; set; }

}

}
