
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AdhocInterviewBatchApplicationV
{

    public int Id { get; set; }

    public Nullable<int> Batch_Id { get; set; }

    public Nullable<int> Application_Id { get; set; }

    public Nullable<bool> SMS_Sent { get; set; }

    public Nullable<int> SMSLog_Id { get; set; }

    public Nullable<bool> IsPresent { get; set; }

    public Nullable<System.DateTime> PresentDatetime { get; set; }

    public Nullable<double> InterviewMarks { get; set; }

    public Nullable<System.DateTime> InterviewMarksDatetime { get; set; }

    public string InterviewMarksByUserId { get; set; }

    public string InterviewMarksBy { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<bool> IsRejected { get; set; }

    public Nullable<System.DateTime> RejectedDatetime { get; set; }

    public Nullable<int> Applicant_Id { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public string MobileNumber { get; set; }

    public string CNIC { get; set; }

    public string CNICDoc { get; set; }

    public Nullable<bool> Hafiz { get; set; }

    public string HifzDocument { get; set; }

    public string PMDCDoc { get; set; }

    public string PMDCNumber { get; set; }

    public Nullable<bool> HifzVerified { get; set; }

    public string DomicileName { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string DesignationName { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public Nullable<int> TotalDays { get; set; }

    public Nullable<int> Days { get; set; }

    public Nullable<int> Months { get; set; }

    public Nullable<int> Years { get; set; }

    public string DistrictName { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

    public string Venue { get; set; }

    public Nullable<bool> PositionHolder { get; set; }

    public Nullable<bool> IsLocked { get; set; }

    public string LockedBy { get; set; }

    public string LockedByUserId { get; set; }

    public Nullable<System.DateTime> LockedDatetime { get; set; }

    public Nullable<int> Position { get; set; }

    public string PositionDoc { get; set; }

    public Nullable<int> PositionMarks { get; set; }

    public Nullable<int> InterviewId { get; set; }

    public string DistrictCode { get; set; }

    public Nullable<bool> IsPostedOnAdhoc { get; set; }

    public Nullable<System.DateTime> PostingDatetime { get; set; }

}

}
