
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AdhocApplicantPMC
{

    public int Id { get; set; }

    public Nullable<int> Applicant_Id { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public string Gender { get; set; }

    public Nullable<System.DateTime> RegistrationDate { get; set; }

    public string RegistrationNo { get; set; }

    public string RegistrationType { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> ValidUpto { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

}

}
