
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AdhocApplicationPreferenceView
{

    public int Id { get; set; }

    public Nullable<int> JobApplication_Id { get; set; }

    public Nullable<int> JobApplicant_Id { get; set; }

    public Nullable<int> JobHF_Id { get; set; }

    public Nullable<int> PreferenceOrder { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

    public string ApplicantName { get; set; }

    public string ApplicantCNIC { get; set; }

    public string HFName { get; set; }

    public string HFMISCode { get; set; }

    public string DistrictName { get; set; }

    public string DistrictCode { get; set; }

    public Nullable<int> HFAC { get; set; }

    public Nullable<int> Job_Id { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string DesignationName { get; set; }

}

}
