
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AdhocApplicationView
{

    public int Id { get; set; }

    public Nullable<int> Applicant_Id { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public string Gender { get; set; }

    public string CNIC { get; set; }

    public string DomicileName { get; set; }

    public string StatusName { get; set; }

    public Nullable<int> Job_Id { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public string HFName { get; set; }

    public string HFMISCode { get; set; }

    public string DistrictName { get; set; }

    public Nullable<int> HFAC { get; set; }

    public Nullable<bool> IsPostedOnAdhoc { get; set; }

    public Nullable<System.DateTime> PostingDatetime { get; set; }

    public Nullable<int> MatricMarks { get; set; }

    public Nullable<int> InterMarks { get; set; }

    public Nullable<int> GraduationMarks { get; set; }

    public Nullable<int> MasterMarks { get; set; }

    public Nullable<int> FirstHigherMarks { get; set; }

    public Nullable<int> SecondHigherMarks { get; set; }

    public Nullable<int> ThirdHigherMarks { get; set; }

    public Nullable<int> HifzMarks { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<int> PositionMarks { get; set; }

    public string PositionDoc { get; set; }

    public Nullable<int> RelevantExpMarks { get; set; }

    public Nullable<int> ExperienceMarks { get; set; }

    public Nullable<int> InterviewMarks { get; set; }

    public Nullable<System.DateTime> MarksDatetime { get; set; }

    public string DesignationName { get; set; }

    public string StatusChangedBy { get; set; }

    public string StatusChangedByUserId { get; set; }

    public Nullable<System.DateTime> StatusChangedDateTime { get; set; }

    public string StatusChangedByDistrict { get; set; }

    public Nullable<int> Status_Id { get; set; }

    public string Status { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<int> Age { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string MobileNumber { get; set; }

    public string Address { get; set; }

    public Nullable<int> GrievanceStatus { get; set; }

    public Nullable<bool> AcceptedByGrievance { get; set; }

    public string GrievanceRemarks { get; set; }

    public Nullable<System.DateTime> GrievanceDateTime { get; set; }

    public Nullable<bool> HifzVerified { get; set; }

    public string HifzVerifiedUserId { get; set; }

    public string HifzVerifiedBy { get; set; }

    public Nullable<System.DateTime> HifzVerifiedDatetime { get; set; }

    public Nullable<bool> PositionVerified { get; set; }

    public string PositionVerifiedUserId { get; set; }

    public string PositionVerifiedBy { get; set; }

    public Nullable<System.DateTime> PositionVerifiedDatetime { get; set; }

}

}
