
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AdhocInterviewBatchApplication
{

    public int Id { get; set; }

    public Nullable<int> Batch_Id { get; set; }

    public Nullable<int> Application_Id { get; set; }

    public Nullable<bool> SMS_Sent { get; set; }

    public Nullable<bool> IsPresent { get; set; }

    public Nullable<System.DateTime> PresentDatetime { get; set; }

    public Nullable<double> InterviewMarks { get; set; }

    public Nullable<System.DateTime> InterviewMarksDatetime { get; set; }

    public string InterviewMarksByUserId { get; set; }

    public string InterviewMarksBy { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<int> SMSLog_Id { get; set; }

    public Nullable<long> MessageId { get; set; }

    public string SMS_Status { get; set; }

    public Nullable<System.DateTime> SMS_StatusCheckTime { get; set; }

    public Nullable<bool> IsRejected { get; set; }

    public Nullable<System.DateTime> RejectedDatetime { get; set; }

    public Nullable<bool> PositionHolder { get; set; }

    public Nullable<int> Position { get; set; }

    public string PositionDoc { get; set; }

    public Nullable<bool> IsLocked { get; set; }

    public Nullable<System.DateTime> LockedDatetime { get; set; }

    public string LockedByUserId { get; set; }

    public string LockedBy { get; set; }



    public virtual AdhocInterviewBatch AdhocInterviewBatch { get; set; }

}

}
