
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ApplicationFileRecosition
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ApplicationFileRecosition()
    {

        this.ApplicationFileRecositionLogs = new HashSet<ApplicationFileRecositionLog>();

    }


    public int Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> Application_Id { get; set; }

    public Nullable<int> RequestStatus_Id { get; set; }

    public int EmpFile_Id { get; set; }

    public Nullable<int> FileUpdated_Id { get; set; }

    public Nullable<int> DDS_Id { get; set; }

    public string Reason { get; set; }

    public Nullable<int> Reason_Id { get; set; }

    public System.DateTime RequestGenDateTime { get; set; }

    public Nullable<System.DateTime> RequestApproveDateTime { get; set; }

    public string RecievedBy { get; set; }

    public string RecievedByContactNo { get; set; }

    public string RecievedByDesig { get; set; }

    public string RecievedByCNIC { get; set; }

    public string ReturnBy { get; set; }

    public string ReturnByContactNo { get; set; }

    public string ReturnByCNIC { get; set; }

    public string ReturnByDesig { get; set; }

    public Nullable<System.DateTime> ReturnDateTime { get; set; }

    public string RecievedByFP { get; set; }

    public string ReturnByFP { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Created_By { get; set; }

    public Nullable<int> Officer_Id { get; set; }

    public string Users_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApplicationFileRecositionLog> ApplicationFileRecositionLogs { get; set; }

}

}
