
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ApplicationFileRecositionLog
{

    public int Id { get; set; }

    public Nullable<int> AFR_Id { get; set; }

    public Nullable<int> FromStatus_Id { get; set; }

    public Nullable<int> ToStatus_Id { get; set; }

    public Nullable<int> Officer_Id { get; set; }

    public string User_Id { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string Remarks { get; set; }



    public virtual ApplicationFileRecosition ApplicationFileRecosition { get; set; }

    public virtual FileRequestStatu FileRequestStatu { get; set; }

    public virtual P_SOfficers P_SOfficers { get; set; }

}

}
