
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ApplicationThumbView
{

    public int Id { get; set; }

    public Nullable<int> ApplicationSource_Id { get; set; }

    public Nullable<int> TrackingNumber { get; set; }

    public Nullable<int> ApplicationType_Id { get; set; }

    public Nullable<int> Status_Id { get; set; }

    public Nullable<int> ForwardingOfficer_Id { get; set; }

    public Nullable<int> PandSOfficer_Id { get; set; }

    public string EmployeeName { get; set; }

    public string CNIC { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public Nullable<int> HealthFacility_Id { get; set; }

    public string HfmisCode { get; set; }

    public string MobileNo { get; set; }

    public string EMaiL { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Created_By { get; set; }

    public string Users_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string ApplicationSourceName { get; set; }

    public string ApplicationTypeName { get; set; }

    public string StatusName { get; set; }

    public Nullable<int> PandSOfficerCode { get; set; }

    public string designationName { get; set; }

    public string HealthFacilityName { get; set; }

    public string DispatchSubject { get; set; }

}

}
