
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ApplicantView
{

    public int Id { get; set; }

    public int Applicant_Status_Id { get; set; }

    public Nullable<int> ApplicationNumber { get; set; }

    public string CNIC { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public string MobileNumber { get; set; }

    public string Address { get; set; }

    public int Domicile_Id { get; set; }

    public string Religion { get; set; }

    public string Gender { get; set; }

    public string MaritalStatus { get; set; }

    public System.DateTime DOB { get; set; }

    public string MobileSec { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

    public string EditedBy { get; set; }

    public Nullable<System.DateTime> EditedDate { get; set; }

    public string PhotoPath { get; set; }

    public string DepartmentMode { get; set; }

    public Nullable<int> CurrentlyworkingHFId { get; set; }

    public string CurrentlyWorkingFacility { get; set; }

    public string workingMode { get; set; }

    public string workingScale { get; set; }

    public string workingDesignation { get; set; }

    public string DomicileName { get; set; }

    public Nullable<int> Age { get; set; }

}

}
