
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AppTypeDoc
{

    public int Document_Id { get; set; }

    public int ApplicationType_Id { get; set; }

    public Nullable<bool> Required { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string User_Id { get; set; }

    public string CreatedBy { get; set; }



    public virtual ApplicationDocument ApplicationDocument { get; set; }

    public virtual ApplicationType ApplicationType { get; set; }

}

}
