
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AppTypePendancy
{

    public int Id { get; set; }

    public Nullable<int> ApplicationType_Id { get; set; }

    public Nullable<bool> IsPendancy { get; set; }

}

}
