
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class AwaitingPostingAppView
{

    public int Id { get; set; }

    public Nullable<int> TrackingNumber { get; set; }

    public string ApplicationType { get; set; }

    public Nullable<int> ForwardingOfficer_Id { get; set; }

    public string Section { get; set; }

    public string Status { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

}

}
