
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class C_ErpUserFields
{

    public long Id { get; set; }

    public Nullable<long> UserModuleComponent_Id { get; set; }

    public string Field_Id { get; set; }



    public virtual C_ErpField C_ErpField { get; set; }

    public virtual C_ErpUserModuleComponents C_ErpUserModuleComponents { get; set; }

}

}
