
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class C_ErpComponent
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public C_ErpComponent()
    {

        this.C_ErpModuleComponents = new HashSet<C_ErpModuleComponents>();

    }


    public string Id { get; set; }

    public Nullable<bool> Value { get; set; }

    public string Name { get; set; }

    public Nullable<int> OrderBy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<C_ErpModuleComponents> C_ErpModuleComponents { get; set; }

}

}
