
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class C_ErpModuleComponents
{

    public long Id { get; set; }

    public string C_ErpModule_Id { get; set; }

    public string C_ErpComponent_Id { get; set; }



    public virtual C_ErpComponent C_ErpComponent { get; set; }

}

}
