
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class C_SessionLog
{

    public long Id { get; set; }

    public string Username { get; set; }

    public string User_Id { get; set; }

    public string IP { get; set; }

    public Nullable<System.DateTime> LoginTime { get; set; }

}

}
