
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class C_UserContact
{

    public int Id { get; set; }

    public string UserId { get; set; }

    public string PhoneNumber { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

    public string CreatedBy { get; set; }

    public string CreatedByUserId { get; set; }

}

}
