
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class C_UserRight
{

    public int Id { get; set; }

    public string User_Id { get; set; }

    public Nullable<bool> AddFacility { get; set; }

    public Nullable<bool> EditFacility { get; set; }

    public Nullable<bool> RemoveFacility { get; set; }

    public Nullable<bool> AddProfile { get; set; }

    public Nullable<bool> EditProfile { get; set; }

    public Nullable<bool> RemoveProfile { get; set; }

    public Nullable<bool> AddVacancy { get; set; }

    public Nullable<bool> EditVacancy { get; set; }

    public Nullable<bool> RemoveVacancy { get; set; }

    public string CreatedBy { get; set; }

    public string CreatedByUserId { get; set; }

    public Nullable<System.DateTime> CreatedDateTime { get; set; }

    public string ModifiedBy { get; set; }

    public string ModifiedByUserId { get; set; }

    public Nullable<System.DateTime> ModifiedDateTime { get; set; }

}

}
