
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class C_UserAuth
{

    public int Id { get; set; }

    public string CNIC { get; set; }

    public string MobileNo { get; set; }

    public string Email { get; set; }

    public Nullable<int> Code { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public Nullable<System.DateTime> ExpiryDateTime { get; set; }

    public Nullable<System.DateTime> VerifyDateTime { get; set; }

}

}
