
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class COVID19Orders
{

    public int ID { get; set; }

    public Nullable<int> Profile_ID { get; set; }

    public string EmployeName { get; set; }

    public Nullable<int> Designation_ID { get; set; }

    public string Designation { get; set; }

    public Nullable<int> District_ID { get; set; }

    public string District { get; set; }

    public Nullable<int> Tehsil_ID { get; set; }

    public string Tehsil { get; set; }

    public Nullable<int> PresentPlaceOfPosting_ID { get; set; }

    public string PresentPlaceOfPosting { get; set; }

    public Nullable<int> GeneralDutyPlaceOfPosting_ID { get; set; }

    public string GeneralDutyPlaceOfPosting { get; set; }

    public Nullable<long> ESR_Id { get; set; }

    public string CNIC { get; set; }

    public string EmployeMode { get; set; }

}

}
