
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class CovidStaffView
{

    public int Id { get; set; }

    public string CNIC { get; set; }

    public Nullable<int> ProfileId { get; set; }

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public string PrevPlaceOfPosting { get; set; }

    public string Designation_Name { get; set; }

    public string WDesignation_Name { get; set; }

    public string Domicile_Name { get; set; }

    public string Gender { get; set; }

    public string Religion_Name { get; set; }

    public string MobileNo { get; set; }

    public string LandlineNo { get; set; }

    public string Address { get; set; }

    public string Tehsil { get; set; }

    public string District { get; set; }

    public string EMaiL { get; set; }

    public string ProfileCNIC { get; set; }

    public Nullable<int> CovidFacilityId { get; set; }

    public string PlaceOfPosting { get; set; }

    public string OriginHealthFacility { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<int> EmpModeId { get; set; }

    public string EmploymentMode { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string CreatedBy { get; set; }

    public string UserId { get; set; }

}

}
