
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class DailyWagerBankDetail
{

    public int Id { get; set; }

    public Nullable<int> DailyWagerProfileId { get; set; }

    public Nullable<int> BankId { get; set; }

    public string AccountTitle { get; set; }

    public string AccountNumber { get; set; }

    public string BankName { get; set; }

}

}
