
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class DailyWagerDetailView
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public string CNIC { get; set; }

    public string Address { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Designation { get; set; }

    public string Gender { get; set; }

    public string MobileNumber { get; set; }

    public Nullable<System.DateTime> ContractStartDate { get; set; }

    public Nullable<System.DateTime> ContractEndDate { get; set; }

    public string ContractImagePath { get; set; }

    public string Division { get; set; }

    public string District { get; set; }

    public string Tehsil { get; set; }

    public string UcCode { get; set; }

    public string DivisionCode { get; set; }

    public string DistirctCode { get; set; }

    public string TehsilCode { get; set; }

    public string HfmisCode { get; set; }

    public Nullable<int> ContractId { get; set; }

    public string UserId { get; set; }

    public string UserName { get; set; }

    public string Category { get; set; }

    public string PersonImage { get; set; }

    public string EmployementMode { get; set; }

}

}
