
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class DDS_Attachments
{

    public int Id { get; set; }

    public Nullable<int> DDs_Id { get; set; }

    public Nullable<bool> Found { get; set; }

    public Nullable<bool> Saved { get; set; }

    public string DDs_Url { get; set; }

    public string LocalPath { get; set; }

}

}
