
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class DDS_Files
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DDS_Files()
    {

        this.DDsDetails = new HashSet<DDsDetail>();

    }


    public int Id { get; set; }

    public string DiaryNo { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string Subject { get; set; }

    public Nullable<double> Status { get; set; }

    public Nullable<double> RequestId { get; set; }

    public string Priority { get; set; }

    public string DepartmentName { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public string FileNIC { get; set; }

    public Nullable<double> MovementId { get; set; }

    public string LegalDocType { get; set; }

    public Nullable<double> LegalDocId { get; set; }

    public Nullable<double> Receiver { get; set; }

    public Nullable<double> DEOId { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public Nullable<int> FileType_Id { get; set; }

    public Nullable<System.DateTime> DateOfJoining { get; set; }

    public string F_Name { get; set; }

    public string F_CNIC { get; set; }

    public Nullable<int> F_Designation_Id { get; set; }

    public Nullable<int> F_BPS { get; set; }

    public Nullable<int> F_BatchNo { get; set; }

    public Nullable<int> F_Section_Id { get; set; }

    public string F_FileNumber { get; set; }

    public string F_Rack { get; set; }

    public string F_Shelf { get; set; }

    public string F_NIC { get; set; }

    public string F_InOutStatus { get; set; }

    public Nullable<int> F_FileType_Id { get; set; }

    public Nullable<System.DateTime> F_DateOfBirth { get; set; }

    public Nullable<System.DateTime> F_DateOfJoining { get; set; }

    public Nullable<System.DateTime> F_Created_Date { get; set; }

    public string F_Created_By { get; set; }

    public string F_Users_Id { get; set; }

    public Nullable<bool> F_IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DDsDetail> DDsDetails { get; set; }

}

}
