
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class DDSDetailsView
{

    public int Id { get; set; }

    public Nullable<int> DDS_Id { get; set; }

    public Nullable<System.DateTime> FromPeriod { get; set; }

    public Nullable<System.DateTime> ToPeriod { get; set; }

    public Nullable<System.DateTime> DCPDate { get; set; }

    public string Remarks { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public string Integrity { get; set; }

    public string Assessment { get; set; }

    public string AdvRemarks { get; set; }

    public string Fitness { get; set; }

    public string RORemarks { get; set; }

    public string CORemarks { get; set; }

    public string ROName { get; set; }

    public string RODesignation { get; set; }

    public string ROPosting { get; set; }

    public string COName { get; set; }

    public string CODesignation { get; set; }

    public string COPosting { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string Users_Id { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

}

}
