
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class District
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public District()
    {

        this.DistrictsDistances = new HashSet<DistrictsDistance>();

        this.DistrictsDistances1 = new HashSet<DistrictsDistance>();

        this.MeritPGDistricts = new HashSet<MeritPGDistrict>();

        this.Merits = new HashSet<Merit>();

        this.MeritsVpDistricts = new HashSet<MeritsVpDistrict>();

    }


    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string OldCode { get; set; }

    public string CapitalTehsilCode { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DistrictsDistance> DistrictsDistances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DistrictsDistance> DistrictsDistances1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritPGDistrict> MeritPGDistricts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Merit> Merits { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritsVpDistrict> MeritsVpDistricts { get; set; }

}

}
