
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class Empattendance
{

    public int ID { get; set; }

    public Nullable<int> IndRegID { get; set; }

    public int ProfileID { get; set; }

    public Nullable<int> SubDept_ID { get; set; }

    public Nullable<int> IsRotation { get; set; }

    public Nullable<int> IsShift { get; set; }

    public Nullable<int> IsHOD { get; set; }

    public Nullable<int> Team_Id { get; set; }

}

}
