
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_Log_View
{

    public int Id { get; set; }

    public Nullable<int> Entity_Id { get; set; }

    public Nullable<int> FK_Id { get; set; }

    public string CNIC_Old { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<int> ProfileStatusId { get; set; }

    public Nullable<int> ProfileEmpModeId { get; set; }

    public Nullable<int> ProfileDesignationId { get; set; }

    public Nullable<int> ProfileHFId { get; set; }

    public Nullable<int> ProfileBPS { get; set; }

    public string UserId { get; set; }

    public string Username { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string CNIC { get; set; }

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public string MobileNo { get; set; }

    public string Designation_Name { get; set; }

    public string EmpMode_Name { get; set; }

    public string StatusName { get; set; }

    public string EmpMode_Name_Old { get; set; }

    public string Designation_Name_Old { get; set; }

    public string StatusName_Old { get; set; }

    public string FullName { get; set; }

    public string DivisionName { get; set; }

    public string DistrictName { get; set; }

    public string TehsilName { get; set; }

    public string Division { get; set; }

    public string District { get; set; }

    public string Tehsil { get; set; }

}

}
