
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_Log
{

    public int Id { get; set; }

    public Nullable<int> Entity_Id { get; set; }

    public Nullable<int> FK_Id { get; set; }

    public string CNIC { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<int> ProfileStatusId { get; set; }

    public Nullable<int> ProfileEmpModeId { get; set; }

    public Nullable<int> ProfileDesignationId { get; set; }

    public Nullable<int> ProfileHFId { get; set; }

    public Nullable<int> ProfileBPS { get; set; }

    public string UserId { get; set; }

    public string Username { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
