
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_Modified_Log
{

    public int Id { get; set; }

    public string Modified_By { get; set; }

    public System.DateTime Modified_Date { get; set; }

    public string Description { get; set; }

    public long Entity_Lifecycle_Id { get; set; }



    public virtual Entity_Lifecycle Entity_Lifecycle { get; set; }

}

}
