
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class EPIDataTemp
{

    public int Id { get; set; }

    public string Province { get; set; }

    public string District { get; set; }

    public string Tehsil { get; set; }

    public string UnionCouncil { get; set; }

    public string HealthFacility { get; set; }

    public Nullable<int> EPICode { get; set; }

}

}
