
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class EpiFacilitiesTemp
{

    public int Id { get; set; }

    public Nullable<int> distcode { get; set; }

    public string district { get; set; }

    public Nullable<int> tehcode { get; set; }

    public string tehsil { get; set; }

    public Nullable<long> uncode { get; set; }

    public string uc { get; set; }

    public Nullable<long> facode { get; set; }

    public string fcname { get; set; }

    public string fatype { get; set; }

}

}
