
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ESRDetail
{

    public int Id { get; set; }

    public Nullable<int> Master_Id { get; set; }

    public string OrderDate { get; set; }

    public Nullable<int> Salary { get; set; }

    public string StartDate { get; set; }

    public string PeriodDuration { get; set; }

    public Nullable<int> Reason_Id { get; set; }

}

}
