
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class EsrSigned
{

    public int Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<long> ESR_Id { get; set; }

    public Nullable<int> ELR_Id { get; set; }

    public string BarcodeNo { get; set; }

    public string Title { get; set; }

    public string Path { get; set; }

    public string Link { get; set; }

    public Nullable<int> MessageLog_Id { get; set; }

    public Nullable<bool> SMS_Sent { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Created_By { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string User_Id { get; set; }

}

}
