
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FCLEAVETDTL
{

    public long ID { get; set; }

    public Nullable<long> MASTER_ID { get; set; }

    public Nullable<System.DateTime> DateFrom { get; set; }

    public Nullable<System.DateTime> DateTo { get; set; }

    public Nullable<int> DAYS { get; set; }

    public string RMKS { get; set; }

    public string SUBJECT { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string CREATED_BY { get; set; }

    public Nullable<System.DateTime> CREATION_DATE { get; set; }

    public string UPDTED_BY { get; set; }

    public Nullable<System.DateTime> UPDATION_DATE { get; set; }



    public virtual FCRequest FCRequest { get; set; }

}

}
