
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FCLEAVETYP
{

    public string PKCODE { get; set; }

    public string NAME { get; set; }

    public string RMKS { get; set; }

    public Nullable<long> ALLOWED { get; set; }

    public Nullable<long> TYPORDER { get; set; }

    public string ENABLE_FLAG { get; set; }

    public string CREATED_BY { get; set; }

    public Nullable<System.DateTime> CREATION_DATE { get; set; }

    public string UPDTED_BY { get; set; }

    public Nullable<System.DateTime> UPDATION_DATE { get; set; }

}

}
