
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FCRequest
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FCRequest()
    {

        this.FCLEAVETDTLs = new HashSet<FCLEAVETDTL>();

        this.FCPromotions = new HashSet<FCPromotion>();

        this.FCTransfers = new HashSet<FCTransfer>();

    }


    public long ID { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public string CNIC { get; set; }

    public string FileNumber { get; set; }

    public string Remarks { get; set; }

    public string ContactProvided { get; set; }

    public string EmailProvided { get; set; }

    public Nullable<long> GSMNetwork_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string CREATED_BY { get; set; }

    public Nullable<System.DateTime> CREATION_DATE { get; set; }

    public string UPDTED_BY { get; set; }

    public Nullable<System.DateTime> UPDATION_DATE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FCLEAVETDTL> FCLEAVETDTLs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FCPromotion> FCPromotions { get; set; }

    public virtual HrProfile HrProfile { get; set; }

    public virtual GSMNETWORK GSMNETWORK { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FCTransfer> FCTransfers { get; set; }

}

}
