
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FCTransfer
{

    public long ID { get; set; }

    public Nullable<long> Master_Id { get; set; }

    public Nullable<long> TrackingNo { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public string FileNumber { get; set; }

    public Nullable<byte> SectionOfficer_Id { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<int> AdditionalSecretary_Id { get; set; }

    public Nullable<int> DeputySec_Id { get; set; }

    public Nullable<int> Secretary_Id { get; set; }

    public Nullable<int> CurrentWorkStep_Id { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string CREATED_BY { get; set; }

    public Nullable<System.DateTime> CREATION_DATE { get; set; }

    public string UPDTED_BY { get; set; }

    public Nullable<System.DateTime> UPDATION_DATE { get; set; }



    public virtual FCRequest FCRequest { get; set; }

}

}
