
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FileMoveDetailView
{

    public int Id { get; set; }

    public Nullable<int> Master_Id { get; set; }

    public Nullable<int> Application_Id { get; set; }

    public Nullable<int> FileUpdated_Id { get; set; }

    public Nullable<int> DDS_Id { get; set; }

    public Nullable<int> FileRequisition_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string DiaryNo { get; set; }

    public string Subject { get; set; }

    public Nullable<double> RequestId { get; set; }

    public string F_Name { get; set; }

    public string F_FileNumber { get; set; }

    public Nullable<int> F_FileType_Id { get; set; }

    public Nullable<int> FromOfficer_Id { get; set; }

    public Nullable<int> ToOfficer_Id { get; set; }

    public string FileName { get; set; }

    public Nullable<int> SenderDiaryNo { get; set; }

    public Nullable<bool> IsRecieved { get; set; }

    public Nullable<System.DateTime> RecievedTime { get; set; }

    public string Col1 { get; set; }

    public string Col2 { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string CreatedBy { get; set; }

    public string User_Id { get; set; }

    public string FromOfficerName { get; set; }

    public string ToOfficerName { get; set; }

    public string DispatchSubject { get; set; }

    public Nullable<int> TrackingNumber { get; set; }

}

}
