
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FileMoveMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FileMoveMaster()
    {

        this.FileMoveDetails = new HashSet<FileMoveDetail>();

    }


    public int Id { get; set; }

    public Nullable<int> MID_Number { get; set; }

    public Nullable<int> FromOfficer_Id { get; set; }

    public Nullable<int> ToOfficer_Id { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string CreatedBy { get; set; }

    public string User_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<bool> IsRecieved { get; set; }

    public Nullable<System.DateTime> RecievedTime { get; set; }

    public Nullable<int> Dispatcher_Id { get; set; }

    public Nullable<int> FileType_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileMoveDetail> FileMoveDetails { get; set; }

}

}
