
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FilesUpdated
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string CNIC { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public Nullable<int> BPS { get; set; }

    public Nullable<int> BatchNo { get; set; }

    public Nullable<int> Section_Id { get; set; }

    public string FileNumber { get; set; }

    public string Rack { get; set; }

    public string Shelf { get; set; }

    public Nullable<int> DDS_Id { get; set; }

    public string NIC { get; set; }

    public string InOutStatus { get; set; }

    public Nullable<int> FileType_Id { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<System.DateTime> DateOfJoining { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Created_By { get; set; }

    public string Users_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
