
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FileMoveMasterView
{

    public int Id { get; set; }

    public Nullable<int> MID_Number { get; set; }

    public Nullable<int> FileType_Id { get; set; }

    public Nullable<int> FromOfficer_Id { get; set; }

    public Nullable<int> ToOfficer_Id { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string CreatedBy { get; set; }

    public string User_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<bool> IsRecieved { get; set; }

    public Nullable<System.DateTime> RecievedTime { get; set; }

    public Nullable<int> Dispatcher_Id { get; set; }

    public Nullable<int> Total { get; set; }

    public string FromOfficerName { get; set; }

    public string FromOfficerDesignationName { get; set; }

    public string ToOfficerName { get; set; }

    public string ToOfficerDesignationName { get; set; }

}

}
