
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class FilesMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FilesMaster()
    {

        this.FileDetails = new HashSet<FileDetail>();

    }


    public int Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> FileType_Id { get; set; }

    public string FileNumber { get; set; }

    public string Name { get; set; }

    public string Barcode { get; set; }

    public string Rack { get; set; }

    public string Shelf { get; set; }

    public string User_Id { get; set; }

    public string Username { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public Nullable<bool> IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileDetail> FileDetails { get; set; }

}

}
