
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class GEOLVL_V
{

    public string PKCODE { get; set; }

    public string FKCODE { get; set; }

    public string CODE { get; set; }

    public string NAME { get; set; }

    public string LVL { get; set; }

    public Nullable<long> LNTH { get; set; }

}

}
