
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HealthFacility
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HealthFacility()
    {

        this.ApplicationRequests = new HashSet<ApplicationRequest>();

        this.HFPhotos = new HashSet<HFPhoto>();

        this.HFWards = new HashSet<HFWard>();

        this.HrProfiles = new HashSet<HrProfile>();

        this.HrProfiles1 = new HashSet<HrProfile>();

        this.HrProfileReqs = new HashSet<HrProfileReq>();

        this.MeritPGs = new HashSet<MeritPG>();

        this.MeritPreferences = new HashSet<MeritPreference>();

        this.Merits = new HashSet<Merit>();

        this.MeritsVps = new HashSet<MeritsVp>();

        this.PSHealthFacilities = new HashSet<PSHealthFacility>();

        this.VPs = new HashSet<VP>();

        this.VPMasters = new HashSet<VPMaster>();

        this.VPSPs = new HashSet<VPSP>();

        this.HFBlocks = new HashSet<HFBlock>();

        this.HFServices = new HashSet<HFService>();

    }


    public int Id { get; set; }

    public string HfmisCode { get; set; }

    public string Name { get; set; }

    public Nullable<long> Entity_Lifecycle_Id { get; set; }

    public int HFAC { get; set; }

    public string PhoneNo { get; set; }

    public string FaxNo { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Status { get; set; }

    public Nullable<double> CoveredArea { get; set; }

    public Nullable<double> UnCoveredArea { get; set; }

    public Nullable<double> ResidentialArea { get; set; }

    public Nullable<double> NonResidentialArea { get; set; }

    public string NA { get; set; }

    public string PP { get; set; }

    public string Mauza { get; set; }

    public string UcName { get; set; }

    public string UcNo { get; set; }

    public Nullable<double> Latitude { get; set; }

    public Nullable<double> Longitude { get; set; }

    public string HfmisOldCode { get; set; }

    public System.Data.Entity.Spatial.DbGeometry GEOM { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApplicationRequest> ApplicationRequests { get; set; }

    public virtual Entity_Lifecycle Entity_Lifecycle { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HFPhoto> HFPhotos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HFWard> HFWards { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HrProfile> HrProfiles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HrProfile> HrProfiles1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HrProfileReq> HrProfileReqs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritPG> MeritPGs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritPreference> MeritPreferences { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Merit> Merits { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritsVp> MeritsVps { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PSHealthFacility> PSHealthFacilities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VP> VPs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VPMaster> VPMasters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VPSP> VPSPs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HFBlock> HFBlocks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HFService> HFServices { get; set; }

}

}
