
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFDistance
{

    public int Id { get; set; }

    public string DistanceTo { get; set; }

    public string OriginName { get; set; }

    public Nullable<double> OriginLatitude { get; set; }

    public Nullable<double> OriginLongitude { get; set; }

    public string FromHFMISCode { get; set; }

    public Nullable<int> FromHF_Id { get; set; }

    public string DestinationName { get; set; }

    public Nullable<double> DestinationLatitude { get; set; }

    public Nullable<double> DestinationLongitude { get; set; }

    public string ToHFMISCode { get; set; }

    public Nullable<int> ToHF_Id { get; set; }

    public string DistanceText { get; set; }

    public Nullable<double> DistanceValue { get; set; }

    public string DurationText { get; set; }

    public Nullable<double> DurationValue { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

}

}
