
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFMode
{

    public int Id { get; set; }

    public string ModeName { get; set; }

    public Nullable<int> Mode_Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

}

}
