
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFOpenedLHRView
{

    public int Id { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public Nullable<int> Seats { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public string Name { get; set; }

    public string DivisionName { get; set; }

    public string DistrictName { get; set; }

    public string TehsilName { get; set; }

    public string HFTypeName { get; set; }

    public string FullName { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Users_Id { get; set; }

    public string Last_Modified_By { get; set; }

}

}
