
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFPicView
{

    public int Id { get; set; }

    public string HfmisCode { get; set; }

    public string Name { get; set; }

    public Nullable<long> Entity_Lifecycle_Id { get; set; }

    public int HFAC { get; set; }

    public string PhoneNo { get; set; }

    public string FaxNo { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Status { get; set; }

    public Nullable<double> CoveredArea { get; set; }

    public Nullable<double> UnCoveredArea { get; set; }

    public Nullable<double> ResidentialArea { get; set; }

    public string NA { get; set; }

    public string PP { get; set; }

    public string Mauza { get; set; }

    public string UcName { get; set; }

    public string UcNo { get; set; }

    public Nullable<double> Latitude { get; set; }

    public Nullable<double> Longitude { get; set; }

    public System.Data.Entity.Spatial.DbGeometry GEOM { get; set; }

    public string HFimage { get; set; }

    public int HFPhoto_HF_ID { get; set; }

    public string FullName { get; set; }

    public string DistrictName { get; set; }

    public string TehsilName { get; set; }

    public string HFTypeName { get; set; }

    public string HFCategoryName { get; set; }

    public Nullable<int> OrderBy { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string HfmisOldCode { get; set; }

}

}
