
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFRecord
{

    public int Id { get; set; }

    public Nullable<int> Facility_Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public Nullable<int> CNIC { get; set; }

    public Nullable<System.DateTime> FromDate { get; set; }

    public Nullable<System.DateTime> ToDate { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

}

}
