
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFService
{

    public int HF_Id { get; set; }

    public string HfmisCode { get; set; }

    public int Services_Id { get; set; }



    public virtual HealthFacility HealthFacility { get; set; }

    public virtual Service Service { get; set; }

}

}
