
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFUCMView
{

    public int Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public Nullable<int> UC_Id { get; set; }

    public string UC { get; set; }

    public Nullable<int> UC_Code { get; set; }

    public Nullable<int> EPI_Code { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

    public string UserId { get; set; }

    public string Username { get; set; }

}

}
