
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFWardBed
{

    public int Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public Nullable<int> Ward_Id { get; set; }

    public Nullable<int> TotalSanctioned { get; set; }

    public Nullable<int> TotalGB { get; set; }

    public Nullable<int> TotalSB { get; set; }

    public Nullable<int> TotalDonated { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }



    public virtual Entity_Lifecycle Entity_Lifecycle { get; set; }

}

}
