
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HFWard
{

    public int Id { get; set; }

    public int HF_Id { get; set; }

    public string Name { get; set; }

    public Nullable<int> NoB { get; set; }

    public Nullable<int> NoGB { get; set; }

    public Nullable<int> NoSB { get; set; }



    public virtual HealthFacility HealthFacility { get; set; }

}

}
