
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HisduEmpAttaundaceLog1
{

    public int ID { get; set; }

    public Nullable<int> IndRegID { get; set; }

    public int HrId { get; set; }

    public string EmployeeName { get; set; }

    public Nullable<System.DateTime> PresentPostingDate { get; set; }

    public string Designation_Name { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<int> Month { get; set; }

    public Nullable<System.DateTime> LogDate { get; set; }

    public Nullable<System.TimeSpan> LogTime { get; set; }

    public Nullable<System.DateTime> DateTimeRecord { get; set; }

    public Nullable<System.DateTime> DateOnlyRecord { get; set; }

    public Nullable<System.DateTime> TimeOnlyRecord { get; set; }

    public Nullable<int> IsLate { get; set; }

    public string Time_In { get; set; }

    public string Time_Out { get; set; }

    public Nullable<int> Seq_No { get; set; }

    public string LogStatus { get; set; }

    public string DName { get; set; }

    public Nullable<int> SubDept_ID { get; set; }

    public Nullable<int> IsRotation { get; set; }

    public string wd { get; set; }

    public Nullable<int> IsHOD { get; set; }

    public Nullable<int> IsShift { get; set; }

}

}
