
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HisduMonthelyEmpReport1
{

    public Nullable<long> Id { get; set; }

    public Nullable<int> HrId { get; set; }

    public string EmployeeName { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<int> Month { get; set; }

    public Nullable<int> TotalLateDay { get; set; }

    public Nullable<decimal> AvailedLate { get; set; }

    public Nullable<decimal> TotalLeave1 { get; set; }

    public Nullable<int> PrasentDay { get; set; }

    public decimal TotalLeave { get; set; }

    public Nullable<decimal> abc { get; set; }

    public Nullable<decimal> TotalSL { get; set; }

    public Nullable<decimal> TotalSick { get; set; }

    public Nullable<decimal> TotalCasual { get; set; }

    public string Designation_Name { get; set; }

    public Nullable<int> SubDept_ID { get; set; }

    public string DName { get; set; }

    public decimal AbsentCount { get; set; }

    public int IsHOD { get; set; }

}

}
