
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HISDU_Projects_CurrentStatus
{

    public int Current_Status_ID { get; set; }

    public string Current_Status { get; set; }

    public Nullable<int> Is_Active { get; set; }

}

}
