
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrApplicationView
{

    public int Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public Nullable<int> ProfileId { get; set; }

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public string CNIC { get; set; }

    public string Designation_Name { get; set; }

    public string EmpMode_Name { get; set; }

    public string StatusName { get; set; }

    public string Domicile_Name { get; set; }

    public string MobileNo { get; set; }

    public string EMaiL { get; set; }

    public string PermanentAddress { get; set; }

    public string CorrespondenceAddress { get; set; }

    public Nullable<int> DesignationId { get; set; }

    public Nullable<int> StatusId { get; set; }

    public string Status { get; set; }

    public string Remarks { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string Username { get; set; }

    public string UserId { get; set; }

}

}
