
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrAttachedPersonView
{

    public int Id { get; set; }

    public Nullable<int> ProfileId { get; set; }

    public Nullable<int> AttachedPersonId { get; set; }

    public string UserId { get; set; }

    public string UserName { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public Nullable<bool> IsDiploma { get; set; }

    public Nullable<bool> OnTraining { get; set; }

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public string CNIC { get; set; }

    public string HfmisCode { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string Designation_Name { get; set; }

    public string EmpMode_Name { get; set; }

    public string WDesignation_Name { get; set; }

    public Nullable<double> Latitude { get; set; }

    public Nullable<double> Longitude { get; set; }

    public Nullable<int> ProfileDesignation_Id { get; set; }

    public string ProfileDesignation_Name { get; set; }

}

}
