
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrDesignation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HrDesignation()
    {

        this.HrProfiles = new HashSet<HrProfile>();

        this.HrProfileReqs = new HashSet<HrProfileReq>();

        this.Merits = new HashSet<Merit>();

        this.MeritsVps = new HashSet<MeritsVp>();

        this.P_SConcernedDesignations = new HashSet<P_SConcernedDesignations>();

        this.PERs = new HashSet<PER>();

        this.PERs1 = new HashSet<PER>();

        this.PromotionJobApplications = new HashSet<PromotionJobApplication>();

        this.PromotionJobApplications1 = new HashSet<PromotionJobApplication>();

        this.SeniorityDetails = new HashSet<SeniorityDetail>();

        this.VPs = new HashSet<VP>();

        this.VPMasters = new HashSet<VPMaster>();

        this.VPSPs = new HashSet<VPSP>();

    }


    public int Id { get; set; }

    public int Code { get; set; }

    public string Name { get; set; }

    public Nullable<int> OrderBy { get; set; }

    public Nullable<int> Cadre_Id { get; set; }

    public Nullable<int> HrScale_Id { get; set; }

    public string Remarks { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Creation_Date { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<int> HrScale_Id2 { get; set; }

    public Nullable<int> OD_Id { get; set; }



    public virtual Cadre Cadre { get; set; }

    public virtual HrScale HrScale { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HrProfile> HrProfiles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HrProfileReq> HrProfileReqs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Merit> Merits { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritsVp> MeritsVps { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<P_SConcernedDesignations> P_SConcernedDesignations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PER> PERs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PER> PERs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PromotionJobApplication> PromotionJobApplications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PromotionJobApplication> PromotionJobApplications1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SeniorityDetail> SeniorityDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VP> VPs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VPMaster> VPMasters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VPSP> VPSPs { get; set; }

}

}
