
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrFileDetail
{

    public long Id { get; set; }

    public long HrFileId { get; set; }

    public string PageName { get; set; }

    public string PageNo { get; set; }

    public string ImagePath { get; set; }

    public Nullable<int> ImageQuality { get; set; }

    public byte[] ImageData { get; set; }

    public long EntityLifeCycleId { get; set; }

}

}
