
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrFocalPerson
{

    public int Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public string Name { get; set; }

    public string CNIC { get; set; }

    public string MobileNumber { get; set; }

    public string Pic { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string Username { get; set; }

    public string UserId { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

}

}
