
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrFp
{

    public int Id { get; set; }

    public string FP1 { get; set; }

    public string FP2 { get; set; }

    public string FP3 { get; set; }

    public string FP4 { get; set; }

    public string FP5 { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public string User_Id { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

}

}
