
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrHealthWorker
{

    public int Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public string CNIC { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string DomicileName { get; set; }

    public Nullable<int> Domicile_Id { get; set; }

    public string Gender { get; set; }

    public string ReligionName { get; set; }

    public Nullable<int> Religion_Id { get; set; }

    public string MobileNo { get; set; }

    public string LandlineNo { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public string HFName { get; set; }

    public string HFMISCode { get; set; }

    public string PresentAddress { get; set; }

    public string UC { get; set; }

    public string PresentAddressTehsilCode { get; set; }

    public string PresentAddressDistrictCode { get; set; }

    public string PresentAddressProvince { get; set; }

    public Nullable<double> PresentAddressLat { get; set; }

    public Nullable<double> PresentAddressLong { get; set; }

    public string PermanentAddressTehsilCode { get; set; }

    public string PermanentAddressDistrictCode { get; set; }

    public string PermanentAddressProvince { get; set; }

    public string PermanentAddress { get; set; }

    public string Nationality { get; set; }

    public string Email { get; set; }

    public string DesignationName { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string CovidJob { get; set; }

    public Nullable<bool> IsHealthWorker { get; set; }

    public string GuardianName { get; set; }

    public string GuardianMiddleName { get; set; }

    public string GuardianLastName { get; set; }

    public string GuardianPhoneNumber { get; set; }

    public string GuardianAddress { get; set; }

    public string GuardianProvince { get; set; }

    public string GuardianTehsilCode { get; set; }

    public string GuardianDistrictCode { get; set; }

    public string GuardianUC { get; set; }

    public string GuardianCNIC { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string CreatedBy { get; set; }

    public string UserId { get; set; }

    public string MobileNetwork { get; set; }

}

}
