
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrInquiryView
{

    public int Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public string Title { get; set; }

    public Nullable<int> Status_Id { get; set; }

    public Nullable<System.DateTime> DateInitiated { get; set; }

    public Nullable<System.DateTime> DateFinalized { get; set; }

    public string Charges { get; set; }

    public string Remarks { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public string OrderNo { get; set; }

    public string Status { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Created_By { get; set; }

    public string Last_Modified_By { get; set; }

    public string Users_Id { get; set; }

}

}
