
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrLeaveRecordView
{

    public int Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<System.DateTime> FromDate { get; set; }

    public Nullable<System.DateTime> ToDate { get; set; }

    public Nullable<int> TotalDays { get; set; }

    public string OrderNumber { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public string OrderFilePath { get; set; }

    public string LeaveType { get; set; }

    public string EmployeeName { get; set; }

    public string CNIC { get; set; }

    public string Designation_Name { get; set; }

    public string WDesignation_Name { get; set; }

    public string Created_By { get; set; }

    public string Users_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

}

}
