
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrProfileReq
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HrProfileReq()
    {

        this.LeaveApplications = new HashSet<LeaveApplication>();

        this.TransferApplications = new HashSet<TransferApplication>();

    }


    public int Id { get; set; }

    public string EmployeeName { get; set; }

    public string CNIC { get; set; }

    public string MobileNo { get; set; }

    public string EMaiL { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public Nullable<int> HealthFacility_Id { get; set; }

    public string HfmisCode { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public bool Approved { get; set; }



    public virtual Entity_Lifecycle Entity_Lifecycle { get; set; }

    public virtual HealthFacility HealthFacility { get; set; }

    public virtual HrDesignation HrDesignation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransferApplication> TransferApplications { get; set; }

}

}
