
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrProfileReq_VIEW
{

    public int Id { get; set; }

    public string EmployeeName { get; set; }

    public string CNIC { get; set; }

    public string MobileNo { get; set; }

    public string EMaiL { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public Nullable<int> HealthFacility_Id { get; set; }

    public string HfmisCode { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public bool Approved { get; set; }

    public string DesignationName { get; set; }

    public string FullName { get; set; }

    public string DistrictName { get; set; }

    public string DivisionName { get; set; }

    public string TehsilName { get; set; }

}

}
