
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrSeniority
{

    public int Id { get; set; }

    public Nullable<int> Category_Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> SeniorityNumber { get; set; }

    public Nullable<int> OldSeniorityNumber { get; set; }

    public Nullable<int> Merit_Id { get; set; }

    public Nullable<int> Status_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

}

}
