
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class HrSeniorityApplicationLog
{

    public int Id { get; set; }

    public string CreatedBy { get; set; }

    public string UserId { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string CNIC_FilePath { get; set; }

    public string ContractOrderCopy_FilePath { get; set; }

    public string PromotionOrderCopy_FilePath { get; set; }

    public string OrderCopy_FilePath { get; set; }

    public string AssumptionReport_FilePath { get; set; }

    public string ContractJoining_FilePath { get; set; }

    public string MeritList_FilePath { get; set; }

    public string Status_FilePath { get; set; }

    public string Description { get; set; }

    public Nullable<int> HrSeniorityApplicationId { get; set; }

}

}
