
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class JobApplicantPrefView
{

    public int Id { get; set; }

    public int Applicant_Id { get; set; }

    public string JobBatchNo { get; set; }

    public int Job_Id { get; set; }

    public int JobFacility_Id { get; set; }

    public int HFId { get; set; }

    public string HFMISCode { get; set; }

    public string FullName { get; set; }

    public int PreferenceOrder { get; set; }

    public bool IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

}

}
