
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class JobPosting
{

    public int Id { get; set; }

    public Nullable<int> Job_Id { get; set; }

    public Nullable<int> JobApplicantion_Id { get; set; }

    public Nullable<int> JobApplicantionPreference_Id { get; set; }

    public Nullable<int> PreferencesNumber { get; set; }

    public Nullable<int> PostingHF_Id { get; set; }

    public string PostingHFMISCode { get; set; }

    public Nullable<int> JobHFSeatNumber { get; set; }

    public Nullable<int> JobHFTotalSeats { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> ESR_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string Remarks { get; set; }



    public virtual Job Job { get; set; }

    public virtual JobApplication JobApplication { get; set; }

    public virtual JobApplicationPreference JobApplicationPreference { get; set; }

}

}
