
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class JobsView
{

    public int Id { get; set; }

    public string Name { get; set; }

    public int Designation_Id { get; set; }

    public int JobLevel_Id { get; set; }

    public System.DateTime Start_date { get; set; }

    public System.DateTime End_date { get; set; }

    public Nullable<bool> PrefrencesAvailable { get; set; }

    public Nullable<int> No_of_Prefrences { get; set; }

    public string Advertisment_Path { get; set; }

    public Nullable<int> Officer_Id { get; set; }

    public Nullable<int> Age_Max { get; set; }

    public Nullable<int> Age_Min { get; set; }

    public string Gender_type { get; set; }

    public Nullable<int> Req_Experience_Years { get; set; }

    public bool IsActive { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Crate_Date { get; set; }

    public string Modified_By { get; set; }

    public Nullable<System.DateTime> Modified_Date { get; set; }

    public int JobDocsStatus_Id { get; set; }

    public string JobType { get; set; }

    public Nullable<int> JobDepartment_Id { get; set; }

    public int PortalForType_Id { get; set; }

    public string JobSubDepartment { get; set; }

    public Nullable<int> JobSubDepartmentId { get; set; }

    public Nullable<int> MainTypeId { get; set; }

}

}
