
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class LawFilesImage
{

    public int ID { get; set; }

    public int FilesID { get; set; }

    public string PhotName { get; set; }

    public bool isDeleted { get; set; }

    public string DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }



    public virtual LawFile LawFile { get; set; }

}

}
