
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class LawWingReport
{

    public int Id { get; set; }

    public Nullable<int> TrackingNumber { get; set; }

    public string CaseNumber { get; set; }

    public string CourtTitle { get; set; }

    public Nullable<System.DateTime> LastDate { get; set; }

    public string Remarks { get; set; }

    public Nullable<System.DateTime> NextDate { get; set; }

    public string Created_By { get; set; }

}

}
