
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class LeaveOrderView
{

    public int Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> LeaveType_Id { get; set; }

    public Nullable<System.DateTime> FromDate { get; set; }

    public Nullable<System.DateTime> ToDate { get; set; }

    public Nullable<int> TotalDays { get; set; }

    public string FileNumber { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public string SignedBy { get; set; }

    public Nullable<byte> Officer_Id { get; set; }

    public Nullable<int> Application_Id { get; set; }

    public string OrderHTML { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public Nullable<int> CombinedOrder_Id { get; set; }

    public int ESRId { get; set; }

    public Nullable<int> ProfileId { get; set; }

    public string EmployeeName { get; set; }

    public string CNIC { get; set; }

    public string Designation { get; set; }

    public string HealthFacility { get; set; }

    public string WorkingHealthFacility { get; set; }

    public Nullable<int> Scale { get; set; }

    public string Contact { get; set; }

    public string OfficerName { get; set; }

    public Nullable<int> TransferTypeID { get; set; }

    public string OrderType { get; set; }

    public string LeaveTypeName { get; set; }

    public string DistrictName { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public string UserName { get; set; }

    public string Last_Modified_By { get; set; }

    public string UserId { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
