
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class LeaveOrder
{

    public int Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> LeaveType_Id { get; set; }

    public Nullable<System.DateTime> FromDate { get; set; }

    public Nullable<System.DateTime> ToDate { get; set; }

    public Nullable<int> TotalDays { get; set; }

    public string FileNumber { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public string SignedBy { get; set; }

    public Nullable<byte> Officer_Id { get; set; }

    public Nullable<int> Application_Id { get; set; }

    public string OrderHTML { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public Nullable<int> CombinedOrder_Id { get; set; }



    public virtual Entity_Lifecycle Entity_Lifecycle { get; set; }

    public virtual EsrSectionOfficer EsrSectionOfficer { get; set; }

    public virtual HrProfile HrProfile { get; set; }

    public virtual LeaveType LeaveType { get; set; }

}

}
