
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class LeaveApplication_View
{

    public long Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> ProfileReq_Id { get; set; }

    public string CNIC { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<int> TrackingNo { get; set; }

    public Nullable<System.DateTime> LeaveStartDate { get; set; }

    public Nullable<System.DateTime> LeaveEndDate { get; set; }

    public Nullable<int> LeaveType_Id { get; set; }

    public Nullable<int> TotalDays { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> LeaveStatus_Id { get; set; }

    public Nullable<byte> SO_Id { get; set; }

    public Nullable<int> DS_Id { get; set; }

    public Nullable<int> AS_Id { get; set; }

    public Nullable<bool> Secretary { get; set; }

    public Nullable<long> EntitylifeCycle_Id { get; set; }

    public string EmployeeName { get; set; }

    public string Designation_Name { get; set; }

    public string LeaveTypeName { get; set; }

    public Nullable<int> Postaanctionedwithscale { get; set; }

    public string HFName { get; set; }

    public string DivisionName { get; set; }

    public string DistrictName { get; set; }

    public string TehsilName { get; set; }

    public string Users_Id { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Last_Modified_By { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string LeaveStatus { get; set; }

    public string SOName { get; set; }

}

}
