
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MeritPreferencesFinal_10_12_2019
{

    public int id { get; set; }

    public int Merit_Id { get; set; }

    public string HfmisCode { get; set; }

    public Nullable<int> PrefrencesOrder { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
