
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MeritPreference
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MeritPreference()
    {

        this.MeritsVps = new HashSet<MeritsVp>();

    }


    public int id { get; set; }

    public int Merit_Id { get; set; }

    public string HfmisCode { get; set; }

    public Nullable<int> PrefrencesOrder { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }



    public virtual HealthFacility HealthFacility { get; set; }

    public virtual Merit Merit { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritsVp> MeritsVps { get; set; }

}

}
