
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MeritPG
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MeritPG()
    {

        this.MeritPGDistricts = new HashSet<MeritPGDistrict>();

    }


    public int Id { get; set; }

    public Nullable<int> Merit_Id { get; set; }

    public Nullable<bool> isPG { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public Nullable<System.DateTime> PGFrom { get; set; }

    public Nullable<int> HealthFacilities_Id { get; set; }

    public string FileName { get; set; }

    public Nullable<int> Specialization_Id { get; set; }

    public string HealthFacilityName { get; set; }



    public virtual HealthFacility HealthFacility { get; set; }

    public virtual Merit Merit { get; set; }

    public virtual Specialization Specialization { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritPGDistrict> MeritPGDistricts { get; set; }

}

}
