
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MeritsVp
{

    public int Id { get; set; }

    public Nullable<int> Merit_Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<int> TotalSanctioned { get; set; }

    public Nullable<int> TotalFilled { get; set; }

    public Nullable<int> TotalVacant { get; set; }

    public Nullable<int> TotalRegular { get; set; }

    public Nullable<int> TotalAdhoc { get; set; }

    public Nullable<int> TotalContract { get; set; }

    public Nullable<int> CurSanctioned { get; set; }

    public Nullable<int> CurFilled { get; set; }

    public Nullable<int> CurVacant { get; set; }

    public Nullable<int> CurRegular { get; set; }

    public Nullable<int> CurAdhoc { get; set; }

    public Nullable<int> CurContract { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> ProcessedDate { get; set; }

    public Nullable<int> MeritActiveDesignation_Id { get; set; }

    public Nullable<int> HrDesignation_Id { get; set; }

    public Nullable<int> MeritPreference_Id { get; set; }

    public Nullable<int> MeritPGDistricts_Id { get; set; }



    public virtual HealthFacility HealthFacility { get; set; }

    public virtual HrDesignation HrDesignation { get; set; }

    public virtual MeritActiveDesignation MeritActiveDesignation { get; set; }

    public virtual MeritPGDistrict MeritPGDistrict { get; set; }

    public virtual MeritPreference MeritPreference { get; set; }

    public virtual Merit Merit { get; set; }

}

}
