
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MeritsVpDistrict
{

    public int Id { get; set; }

    public Nullable<int> MeritVpDistrictId { get; set; }

    public string MeritVpDistrictCode { get; set; }

    public Nullable<int> Vacant { get; set; }

    public Nullable<int> MeritActiveDesgId { get; set; }



    public virtual District District { get; set; }

    public virtual MeritActiveDesignation MeritActiveDesignation { get; set; }

}

}
