
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MeritDiplomaCandidateView
{

    public int meritDiplomaId { get; set; }

    public string CNIC { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<int> DesignationId { get; set; }

    public Nullable<int> HfId { get; set; }

    public Nullable<int> DistrictId { get; set; }

    public Nullable<double> Marks { get; set; }

    public string PhoneNumber { get; set; }

    public Nullable<int> ProfileId { get; set; }

    public string Rollno { get; set; }

    public string UploadPath { get; set; }

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public string EmpMode_Name { get; set; }

    public string Cadre_Name { get; set; }

    public string FullName { get; set; }

    public string UserId { get; set; }

}

}
