
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MeritPGView
{

    public int Id { get; set; }

    public Nullable<int> Merit_Id { get; set; }

    public Nullable<bool> isPG { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public Nullable<System.DateTime> PGFrom { get; set; }

    public Nullable<int> HealthFacilities_Id { get; set; }

    public string FileName { get; set; }

    public Nullable<int> Specialization_Id { get; set; }

    public string HealthFacilityName { get; set; }

    public string SpecializationName { get; set; }

}

}
