
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class Merit
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Merit()
    {

        this.MeritGrieviences = new HashSet<MeritGrievience>();

        this.MeritPGs = new HashSet<MeritPG>();

        this.MeritPGDistricts = new HashSet<MeritPGDistrict>();

        this.MeritPreferences = new HashSet<MeritPreference>();

        this.MeritsVps = new HashSet<MeritsVp>();

    }


    public int Id { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string Status { get; set; }

    public string OfferLetterPath { get; set; }

    public string OfferLetterKey { get; set; }

    public Nullable<System.DateTime> OfferLetterKeyExpiry { get; set; }

    public Nullable<int> MeritNumber { get; set; }

    public Nullable<int> ApplicationNumber { get; set; }

    public string CNIC { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public string MobileNumber { get; set; }

    public string Address { get; set; }

    public Nullable<long> EntityLifecylcle_Id { get; set; }

    public string PMDCNumber { get; set; }

    public Nullable<int> MeritsActiveDesignationId { get; set; }

    public string PPSCNumber { get; set; }

    public Nullable<System.DateTime> PPSCDate { get; set; }

    public string LetterNumber { get; set; }

    public Nullable<System.DateTime> LetterDate { get; set; }

    public Nullable<System.DateTime> PreferencesDate { get; set; }

    public Nullable<int> District_Id { get; set; }

    public Nullable<bool> IsDisabled { get; set; }

    public Nullable<int> PPSCSrNo { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public string WorkingStatus { get; set; }

    public string GrievanceLetter { get; set; }

    public Nullable<bool> DiplomaOffer { get; set; }

    public Nullable<int> Domicile_Id { get; set; }

    public Nullable<int> Religion_Id { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string MaritalStatus { get; set; }

    public string MobileSec { get; set; }



    public virtual District District { get; set; }

    public virtual HealthFacility HealthFacility { get; set; }

    public virtual HrDesignation HrDesignation { get; set; }

    public virtual MeritActiveDesignation MeritActiveDesignation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritGrievience> MeritGrieviences { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritPG> MeritPGs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritPGDistrict> MeritPGDistricts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritPreference> MeritPreferences { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MeritsVp> MeritsVps { get; set; }

}

}
