
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MessageLog
{

    public int Id { get; set; }

    public string Text { get; set; }

    public string SentTo { get; set; }

    public string SentFrom { get; set; }

    public string Response { get; set; }

    public string FKId { get; set; }

    public Nullable<System.DateTime> SentDate { get; set; }

    public string MessageType { get; set; }

}

}
