
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MWRouteView
{

    public int Id { get; set; }

    public Nullable<int> SourceId { get; set; }

    public string SourceName { get; set; }

    public Nullable<double> SourceLatitude { get; set; }

    public Nullable<double> SourceLongitude { get; set; }

    public Nullable<int> DestinationId { get; set; }

    public string DestinationName { get; set; }

    public Nullable<double> DestinationLatitude { get; set; }

    public Nullable<double> DestinationLongitude { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UserId { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
