
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class MWRouteDetail
{

    public int Id { get; set; }

    public Nullable<int> PointTypeId { get; set; }

    public Nullable<int> RouteId { get; set; }

    public Nullable<double> Latitude { get; set; }

    public Nullable<double> Longitude { get; set; }

    public Nullable<double> DistanceFromDestination { get; set; }

    public string DistanceFromDestinationText { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UserId { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
