
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class PandSOfficerView
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string CNIC { get; set; }

    public Nullable<int> FingerPrint_Id { get; set; }

    public string Contact { get; set; }

    public string DesignationName { get; set; }

    public string Program { get; set; }

    public Nullable<int> Code { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string User_Id { get; set; }

    public Nullable<int> OrderBy { get; set; }

    public string HrDesignationName { get; set; }

    public string CadreName { get; set; }

    public Nullable<int> Scale { get; set; }

    public string UserName { get; set; }

    public string UserDetail { get; set; }

}

}
