
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class PER
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PER()
    {

        this.PerGradings = new HashSet<PerGrading>();

        this.PerImages = new HashSet<PerImage>();

        this.PerPrfmAssments = new HashSet<PerPrfmAssment>();

        this.PerTargetAchievements = new HashSet<PerTargetAchievement>();

        this.PerTrainings = new HashSet<PerTraining>();

    }


    public int Id { get; set; }

    public int PerType_Id { get; set; }

    public int HrProfile_Id { get; set; }

    public Nullable<int> LeaveType_Id { get; set; }

    public int PostHeld { get; set; }

    public int Scale { get; set; }

    public int Year { get; set; }

    public System.DateTime FromPeriod { get; set; }

    public System.DateTime ToPeriod { get; set; }

    public string Duties { get; set; }

    public string ExceptionalContribution { get; set; }

    public string MoreEffective { get; set; }

    public string PenPicture { get; set; }

    public string CoName { get; set; }

    public Nullable<int> CoDesignation_Id { get; set; }

    public Nullable<System.DateTime> CoDate { get; set; }

    public string RoName { get; set; }

    public Nullable<int> RoDesignation_Id { get; set; }

    public Nullable<System.DateTime> RoDate { get; set; }

    public int EntityLifecycle_Id { get; set; }



    public virtual HrDesignation HrDesignation { get; set; }

    public virtual HrDesignation HrDesignation1 { get; set; }

    public virtual HrProfile HrProfile { get; set; }

    public virtual LeaveType LeaveType { get; set; }

    public virtual PerType PerType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PerGrading> PerGradings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PerImage> PerImages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PerPrfmAssment> PerPrfmAssments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PerTargetAchievement> PerTargetAchievements { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PerTraining> PerTrainings { get; set; }

}

}
