
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class PerInquiry
{

    public int Id { get; set; }

    public int Profile_Id { get; set; }

    public string Remarks { get; set; }

    public string Punishment { get; set; }

    public bool isResolved { get; set; }

    public int Entity_Lifecycle { get; set; }

    public bool isDeleted { get; set; }

    public string DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }



    public virtual HrProfile HrProfile { get; set; }

}

}
