
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class PermotionReport
{

    public int Id { get; set; }

    public string AppliedForDesignationName { get; set; }

    public string AppliedForDesignationSrName { get; set; }

    public string CNIC { get; set; }

    public string CurrentDesignationName { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string MobileNumber { get; set; }

    public string DistrictName { get; set; }

    public string HfName { get; set; }

    public Nullable<System.DateTime> PromotionToCurrentScale { get; set; }

    public string SeniorityNo { get; set; }

    public string Certificate_Of_Working { get; set; }

    public string No_Enquiry_Ceritificate { get; set; }

    public string MatricFScMbbsDegree { get; set; }

    public string Postgraduate_Degree { get; set; }

    public string PMDC { get; set; }

    public string No_Enquiry_Certifcate_Attested_ { get; set; }

    public string Service_Statments { get; set; }

}

}
