
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class PHFMCOrder
{

    public int Id { get; set; }

    public Nullable<int> ProfileId { get; set; }

    public Nullable<long> ESRId { get; set; }

    public Nullable<int> ELRId { get; set; }

    public string RequestedBy { get; set; }

    public string RequestedByUserId { get; set; }

    public Nullable<System.DateTime> RequestTime { get; set; }

    public Nullable<bool> IsApproved { get; set; }

    public Nullable<System.DateTime> ApprovalTime { get; set; }

    public string ApprovalBy { get; set; }

    public string ApprovalByUserId { get; set; }

    public Nullable<bool> OrderGenerated { get; set; }

    public Nullable<System.DateTime> OrderTime { get; set; }

    public string OrderByUserId { get; set; }

    public string OrderBy { get; set; }

    public Nullable<bool> IsSigned { get; set; }

    public string SignedByUserId { get; set; }

    public string SignedByUser { get; set; }

    public string SignedOrderPath { get; set; }

    public Nullable<System.DateTime> SignedOrderTime { get; set; }

    public Nullable<bool> Downloaded { get; set; }

    public string DownloadByUserId { get; set; }

    public string DownloadByUser { get; set; }

    public Nullable<System.DateTime> DownloadTime { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
