
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class Pivot_Dsg_Specific
{

    public int Id { get; set; }

    public Nullable<int> MO { get; set; }

    public Nullable<int> WMO { get; set; }

    public Nullable<int> SMO { get; set; }

    public Nullable<int> APMO { get; set; }

    public Nullable<int> MS { get; set; }

    public Nullable<int> SWMO { get; set; }

    public Nullable<int> APWMO { get; set; }

}

}
