
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ProfileThumbView
{

    public int Id { get; set; }

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public string CNIC { get; set; }

    public Nullable<int> JoiningGradeBPS { get; set; }

    public Nullable<int> CurrentGradeBPS { get; set; }

    public string MobileNo { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string Status { get; set; }

    public Nullable<int> Status_Id { get; set; }

    public Nullable<int> Cadre_Id { get; set; }

    public string HfmisCode { get; set; }

    public string CadreName { get; set; }

    public int Designation_Id { get; set; }

    public string Designation_Name { get; set; }

    public int EmpMode_Id { get; set; }

    public string EmpMode_Name { get; set; }

    public string HealthFacility { get; set; }

    public string WorkingHealthFacility { get; set; }

    public Nullable<int> WDesignation_Id { get; set; }

    public string working_Designation_Name { get; set; }

}

}
