
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class PromotionApplyView
{

    public int Id { get; set; }

    public string User_Id { get; set; }

    public string CNIC { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public string Status { get; set; }

    public string AcceptancePath { get; set; }

    public Nullable<int> ToDesignation_Id { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public Nullable<System.DateTime> RegisterTime { get; set; }

    public Nullable<System.DateTime> ProfileReviewTime { get; set; }

    public Nullable<System.DateTime> AcceptanceTime { get; set; }

    public Nullable<System.DateTime> CompletedTime { get; set; }

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string Province { get; set; }

    public string MaritalStatus { get; set; }

    public string BloodGroup { get; set; }

    public string SeniorityNo { get; set; }

    public string PersonnelNo { get; set; }

    public Nullable<int> JoiningGradeBPS { get; set; }

    public Nullable<int> CurrentGradeBPS { get; set; }

    public string ToDesignationName { get; set; }

    public string DesignationName { get; set; }

    public string WDesignationName { get; set; }

    public string UserName { get; set; }

}

}
