
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class PromotionApply
{

    public int Id { get; set; }

    public string User_Id { get; set; }

    public string CNIC { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public string Status { get; set; }

    public string AcceptancePath { get; set; }

    public Nullable<int> ToDesignation_Id { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public Nullable<System.DateTime> RegisterTime { get; set; }

    public Nullable<System.DateTime> ProfileReviewTime { get; set; }

    public Nullable<System.DateTime> AcceptanceTime { get; set; }

    public Nullable<System.DateTime> CompletedTime { get; set; }

}

}
