
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class PromotionEsrView
{

    public long Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<long> BPSFrom { get; set; }

    public Nullable<long> BPSTo { get; set; }

    public Nullable<int> DesignationFrom { get; set; }

    public Nullable<int> DesignationTo { get; set; }

    public Nullable<int> DepartmentFrom { get; set; }

    public Nullable<int> DepartmentTo { get; set; }

    public string HfmisCodeFrom { get; set; }

    public string HfmisCodeTo { get; set; }

    public string Remarks { get; set; }

    public string COMMENTS { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public string DepartmentFromName { get; set; }

    public string DepartmentToName { get; set; }

    public string DesignationFromName { get; set; }

    public string DesignationToName { get; set; }

    public string HealthFacilityFromName { get; set; }

    public string HealthFacilityToName { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

}

}
