
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class SeniorityDetail
{

    public int Id { get; set; }

    public Nullable<int> SeniorityMaster_Id { get; set; }

    public string SeniorityNo { get; set; }

    public string SeniorityNoOld { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<int> YearOfJoining { get; set; }

    public string Domicile { get; set; }

    public Nullable<System.DateTime> DateOfAppointment { get; set; }

    public string PlaceOfPosting { get; set; }

    public Nullable<int> PPSCMerit { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string Status { get; set; }

    public string Grievance { get; set; }

    public string SupportingDocs { get; set; }



    public virtual HrDesignation HrDesignation { get; set; }

    public virtual HrProfile HrProfile { get; set; }

    public virtual SeniorityMaster SeniorityMaster { get; set; }

}

}
