
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class SeniorityMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SeniorityMaster()
    {

        this.SeniorityDetails = new HashSet<SeniorityDetail>();

    }


    public int Id { get; set; }

    public string FileName { get; set; }

    public Nullable<int> TotalApplicants { get; set; }

    public Nullable<System.DateTime> DateStart { get; set; }

    public string IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SeniorityDetail> SeniorityDetails { get; set; }

}

}
