
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class SHMEDVP
{

    public int Id { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public string HealthFacilityName { get; set; }

    public string District { get; set; }

    public Nullable<int> Sanctioned { get; set; }

    public Nullable<int> Filled { get; set; }

    public Nullable<int> ReservedMaleNurse { get; set; }

    public Nullable<int> Vacant { get; set; }

    public Nullable<int> Regular { get; set; }

    public Nullable<int> Contract { get; set; }

    public Nullable<int> Adhoc { get; set; }

}

}
