
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class SignedOrder
{

    public int Id { get; set; }

    public Nullable<System.DateTime> UploadDate { get; set; }

    public Nullable<int> Section_Id { get; set; }

    public string SectionName { get; set; }

    public Nullable<int> ESR_Id { get; set; }

    public Nullable<int> ELR_Id { get; set; }

    public string Title { get; set; }

    public string data { get; set; }

    public Nullable<System.DateTime> InsDT { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<int> User_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
