
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class SMS_Session
{

    public int Id { get; set; }

    public string SessionId { get; set; }

    public Nullable<System.DateTime> LastActivityTime { get; set; }

    public Nullable<System.DateTime> RequestDateTime { get; set; }

    public string RequestedBy { get; set; }

}

}
