
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class SMS_Log
{

    public int Id { get; set; }

    public Nullable<int> SMS_Session_Id { get; set; }

    public string MessageId { get; set; }

    public string Number { get; set; }

    public string Message { get; set; }

    public Nullable<int> FKId { get; set; }

    public string Status { get; set; }

    public string Mask { get; set; }

    public string UserId { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

}

}
