
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class tEMPtABLE
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Husband { get; set; }

    public string CNIC { get; set; }

    public string Mobile { get; set; }

    public string Designation { get; set; }

    public string Address { get; set; }

    public string Division { get; set; }

    public string District { get; set; }

    public string Town { get; set; }

    public string UC { get; set; }

    public string Gender { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string Bank { get; set; }

    public string AccountTitle { get; set; }

    public string ACNO { get; set; }

    public Nullable<System.DateTime> STARTcONTRAC { get; set; }

    public Nullable<System.DateTime> ENDCONTRACT { get; set; }

    public Nullable<bool> RecordStatus { get; set; }

    public string Category { get; set; }

    public string Empmode { get; set; }

    public string UserNAme { get; set; }

}

}
