
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class TransferApplication
{

    public long Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> ProfileReq_Id { get; set; }

    public string CNIC { get; set; }

    public string ToHF_Id { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<int> TrackingNo { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> ApplicationStatus_Id { get; set; }

    public Nullable<byte> SO_Id { get; set; }

    public Nullable<int> DS_Id { get; set; }

    public Nullable<int> AS_Id { get; set; }

    public Nullable<bool> Secretary { get; set; }

    public Nullable<long> EntitylifeCycle_Id { get; set; }



    public virtual Entity_Lifecycle Entity_Lifecycle { get; set; }

    public virtual EsrSectionOfficer EsrSectionOfficer { get; set; }

    public virtual HrProfile HrProfile { get; set; }

    public virtual HrProfileReq HrProfileReq { get; set; }

    public virtual TransferAppliationStatu TransferAppliationStatu { get; set; }

}

}
