
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class TransferOrder
{

    public int id { get; set; }

    public Nullable<System.DateTime> UploadedDate { get; set; }

    public string Date { get; set; }

    public string Section { get; set; }

    public string BarCodeNo { get; set; }

    public string data { get; set; }

    public Nullable<System.DateTime> InsDT { get; set; }

    public Nullable<int> Type { get; set; }

}

}
