
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class UCWiseData
{

    public int Id { get; set; }

    public Nullable<int> Sr { get; set; }

    public string Division { get; set; }

    public string District { get; set; }

    public string Tehsil { get; set; }

    public string Area { get; set; }

    public string UCNo { get; set; }

    public string UCName { get; set; }

    public Nullable<int> TotalPopulationMale { get; set; }

    public Nullable<int> TotalPopulationFemale { get; set; }

    public Nullable<int> TotalPopulation { get; set; }

    public Nullable<int> PartiallyVaccinateMale { get; set; }

    public Nullable<int> PartiallyCaccinatedFemale { get; set; }

    public Nullable<int> TotalPartiallyVaccinated { get; set; }

    public Nullable<int> FullyVaccinatedMale { get; set; }

    public Nullable<int> FullyVaccinatedFemale { get; set; }

    public Nullable<int> TotalFullyVaccinated { get; set; }

    public Nullable<int> TargetTobeVaccinated1stDose { get; set; }

    public string TehsilCode { get; set; }

    public Nullable<bool> RecordStatus { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }

    public string DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedAt { get; set; }

}

}
