
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class UsersViewNew
{

    public string Id { get; set; }

    public string DivisionID { get; set; }

    public string DistrictID { get; set; }

    public string TehsilID { get; set; }

    public string hfmiscode { get; set; }

    public int LevelID { get; set; }

    public Nullable<int> DesigCode { get; set; }

    public bool isActive { get; set; }

    public string HfmisCodeNew { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public Nullable<decimal> CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<decimal> ModifiedBy { get; set; }

    public string UserDetail { get; set; }

    public string responsibleuser { get; set; }

    public string UserName { get; set; }

    public string hashynoty { get; set; }

    public string HfTypeCode { get; set; }

    public string Email { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public bool isUpdated { get; set; }

    public string Cnic { get; set; }

    public int ProfileId { get; set; }

    public string Role_Name { get; set; }

}

}
