
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class UserInformation
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string EnrollNumber { get; set; }

    public string MachineNumber { get; set; }

    public Nullable<int> FingerIndex { get; set; }

    public string TmpData { get; set; }

    public string Enabled { get; set; }

}

}
