
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ViewProfilePhoto
{

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public string CNIC { get; set; }

    public string Designation_Name { get; set; }

    public string MobileNo { get; set; }

    public string StatusName { get; set; }

    public string DistrictName { get; set; }

    public string TehsilName { get; set; }

    public string FullName { get; set; }

    public string HFTypeName { get; set; }

    public string ProfilePhoto { get; set; }

}

}
