
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ViewESRSummaryTotal
{

    public long Rn { get; set; }

    public string DISTRICT { get; set; }

    public Nullable<int> MutualTransfer { get; set; }

    public Nullable<int> AtDiposal { get; set; }

    public Nullable<int> Suspend { get; set; }

    public Nullable<int> General { get; set; }

    public Nullable<int> CustomOrder { get; set; }

    public Nullable<int> GrandTotal { get; set; }

}

}
