
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ViewMeritsVp
{

    public int Id { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string Status { get; set; }

    public string OfferLetterPath { get; set; }

    public string OfferLetterKey { get; set; }

    public Nullable<System.DateTime> OfferLetterKeyExpiry { get; set; }

    public Nullable<int> MeritNumber { get; set; }

    public Nullable<int> ApplicationNumber { get; set; }

    public string CNIC { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string FatherName { get; set; }

    public string MobileNumber { get; set; }

    public string Address { get; set; }

    public Nullable<long> EntityLifecylcle_Id { get; set; }

    public string PMDCNumber { get; set; }

    public Nullable<int> MeritsActiveDesignationId { get; set; }

    public string PPSCNumber { get; set; }

    public Nullable<System.DateTime> PPSCDate { get; set; }

    public string LetterNumber { get; set; }

    public Nullable<System.DateTime> LetterDate { get; set; }

    public Nullable<System.DateTime> PreferencesDate { get; set; }

    public Nullable<int> District_Id { get; set; }

    public Nullable<bool> IsDisabled { get; set; }

    public Nullable<int> PPSCSrNo { get; set; }

    public Nullable<int> HF_Id { get; set; }

    public string WorkingStatus { get; set; }

    public string GrievanceLetter { get; set; }

    public Nullable<bool> DiplomaOffer { get; set; }

    public string DomicileDistrict { get; set; }

    public Nullable<int> MeritPgId { get; set; }

    public Nullable<bool> isPG { get; set; }

    public Nullable<System.DateTime> PGFrom { get; set; }

    public string FileName { get; set; }

    public Nullable<int> MeritVpId { get; set; }

    public Nullable<int> DsgId { get; set; }

    public string DsgName { get; set; }

    public Nullable<int> DsgScale { get; set; }

    public string DivisionCode { get; set; }

    public string DivisionName { get; set; }

    public string DistrictCode { get; set; }

    public string DistrictName { get; set; }

    public string TehsilCode { get; set; }

    public string TehsilName { get; set; }

    public string HFTypeCode { get; set; }

    public string HFTypeName { get; set; }

    public Nullable<int> VpHFId { get; set; }

    public string VpHFMISCode { get; set; }

    public string FullName { get; set; }

    public Nullable<int> TotalSanctioned { get; set; }

    public Nullable<int> TotalFilled { get; set; }

    public Nullable<int> TotalVacant { get; set; }

    public Nullable<int> TotalRegular { get; set; }

    public Nullable<int> TotalAdhoc { get; set; }

    public Nullable<int> TotalContract { get; set; }

    public Nullable<int> CurSanctioned { get; set; }

    public Nullable<int> CurFilled { get; set; }

    public Nullable<int> CurVacant { get; set; }

    public Nullable<int> CurAdhoc { get; set; }

    public Nullable<int> CurContract { get; set; }

    public string MeritVpStatus { get; set; }

    public Nullable<int> MeritPrefrenceId { get; set; }

    public Nullable<int> MeritPreferenceHFId { get; set; }

    public string MeritPrefrenceHfmisCode { get; set; }

    public Nullable<int> PrefrencesOrder { get; set; }

    public Nullable<int> MeritPGDistrictsId { get; set; }

    public Nullable<int> MeritPGDistricts_Districts_Id { get; set; }

    public Nullable<int> DistrictsPrefrencesOrder { get; set; }

}

}
