
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class ViewHFService
{

    public string DivisionName { get; set; }

    public string DistrictName { get; set; }

    public string TehsilName { get; set; }

    public string HFMISCode { get; set; }

    public string FullName { get; set; }

    public string HFTypeCode { get; set; }

    public string HFTypeName { get; set; }

    public Nullable<int> C24_Hour_Emergency { get; set; }

    public Nullable<int> C3_D_Imaging_System { get; set; }

    public Nullable<int> A_E_Department { get; set; }

    public Nullable<int> Accident___Emergency_Nursing_Course { get; set; }

    public Nullable<int> Acrylic_Crown_ { get; set; }

    public Nullable<int> AIDS_Control_Program { get; set; }

    public Nullable<int> Air_Conditioner_for_OT { get; set; }

    public Nullable<int> All_Pathology_Tests_including_PCR_and_Histopathology { get; set; }

    public Nullable<int> All_Type_Biochemstry_of_Blood { get; set; }

    public Nullable<int> All_Type_of_X_Rays { get; set; }

    public Nullable<int> Altra_Sound { get; set; }

    public Nullable<int> Altrasonographic { get; set; }

    public Nullable<int> AltraSound_Machine { get; set; }

    public Nullable<int> Altrasound_Section { get; set; }

    public Nullable<int> Alveolar_Fracture_ { get; set; }

    public Nullable<int> Alvolectomy { get; set; }

    public Nullable<int> Ambu_bag { get; set; }

    public Nullable<int> Ambulance { get; set; }

    public Nullable<int> Ambulance_Service { get; set; }

    public Nullable<int> Anaesthesia { get; set; }

    public Nullable<int> ANC { get; set; }

    public Nullable<int> Anesthesia_Machine { get; set; }

    public Nullable<int> Angiography_ { get; set; }

    public Nullable<int> Angioplasty { get; set; }

    public Nullable<int> Audiological_Diagnostic_test { get; set; }

    public Nullable<int> Audiology { get; set; }

    public Nullable<int> Audiometery__ENT_Test_ { get; set; }

    public Nullable<int> Auto_Clave { get; set; }

    public Nullable<int> Autopsy_services { get; set; }

    public Nullable<int> Azeem_Facility { get; set; }

    public Nullable<int> B_Scan_Ultrasound__Eye_Test_ { get; set; }

    public Nullable<int> Baby_Warmer { get; set; }

    public Nullable<int> basic_diagnostic { get; set; }

    public Nullable<int> Basic_Health_Unit_Chak_No_148_6R { get; set; }

    public Nullable<int> Basic_Lab { get; set; }

    public Nullable<int> BHU_117_6R { get; set; }

    public Nullable<int> BHU_132_6_R { get; set; }

    public Nullable<int> BHU_137_6R { get; set; }

    public Nullable<int> BHU_142_6_R { get; set; }

    public Nullable<int> BHU_154_3L { get; set; }

    public Nullable<int> BHU_160_7_R { get; set; }

    public Nullable<int> BHU_438_6_R { get; set; }

    public Nullable<int> BHU_99_6_R { get; set; }

    public Nullable<int> BHU_Mangowal { get; set; }

    public Nullable<int> Biochemestry_General___Special { get; set; }

    public Nullable<int> Biochemistry_Complete_Tests { get; set; }

    public Nullable<int> Biometry__Eye_Test_ { get; set; }

    public Nullable<int> Biopsy_Test { get; set; }

    public Nullable<int> Blood_Bank { get; set; }

    public Nullable<int> Blood_Complete__PT_APTT__INR_ { get; set; }

    public Nullable<int> BLOOD_GAS_ANALYZER { get; set; }

    public Nullable<int> Blood_Grouping { get; set; }

    public Nullable<int> Blood_screening { get; set; }

    public Nullable<int> Blood_Sugar { get; set; }

    public Nullable<int> Blood_Test { get; set; }

    public Nullable<int> Blood_Transfusion { get; set; }

    public Nullable<int> BLOOD_TRANSFUSION_SERVICES { get; set; }

    public Nullable<int> Breast_Clinic { get; set; }

    public Nullable<int> Bridge_3_untis_porcelain_ { get; set; }

    public Nullable<int> Bridge_three_unit_Porcelain_ { get; set; }

    public Nullable<int> BRONCHOSCOPY { get; set; }

    public Nullable<int> BSF { get; set; }

    public Nullable<int> BSR { get; set; }

    public Nullable<int> Buccal_Smear_Test { get; set; }

    public Nullable<int> Bulb_Sucker { get; set; }

    public Nullable<int> C_R__System { get; set; }

    public Nullable<int> C_T_SCAN { get; set; }

    public Nullable<int> Calposocopy { get; set; }

    public Nullable<int> Cardiac_Care_Nursing_Course { get; set; }

    public Nullable<int> Cardiac_Catheterization___Intervention { get; set; }

    public Nullable<int> Cardiac_Monitor { get; set; }

    public Nullable<int> Cardiac_Surgery { get; set; }

    public Nullable<int> Cardiological_Tests_e_g__ETT__Echo__ECG { get; set; }

    public Nullable<int> Cardiology { get; set; }

    public Nullable<int> Casualty_of_Department { get; set; }

    public Nullable<int> CATH_LAB { get; set; }

    public Nullable<int> CCU { get; set; }

    public Nullable<int> Central_Steriliation_Services__CSSD_ { get; set; }

    public Nullable<int> CEPH__Cephalometric_Analysis_ { get; set; }

    public Nullable<int> Chemical_Pathology { get; set; }

    public Nullable<int> Chemistry_Analysier { get; set; }

    public Nullable<int> Chemotherapy_Radiation__Cancer_Patients_ { get; set; }

    public Nullable<int> Clinical_Labortary { get; set; }

    public Nullable<int> COD { get; set; }

    public Nullable<int> Colonoscopy__Endoscopy_ { get; set; }

    public Nullable<int> Colour_Doppler { get; set; }

    public Nullable<int> Compound_Filling_ { get; set; }

    public Nullable<int> Computer { get; set; }

    public Nullable<int> Consultant___Clinical_Support_to_Sir_Ganga_Ram_Hospital_Lahore_ { get; set; }

    public Nullable<int> Contrast_Studies { get; set; }

    public Nullable<int> CP_ESR { get; set; }

    public Nullable<int> CRP__ASOT__RA_Factor { get; set; }

    public Nullable<int> CRS__Cassette_Radiographic_System_ { get; set; }

    public Nullable<int> C_Section { get; set; }

    public Nullable<int> CSSD { get; set; }

    public Nullable<int> CT_SCAN__equipped_with_an_automated_contrast_injector_ { get; set; }

    public Nullable<int> CT_Scan_All_Kinds { get; set; }

    public Nullable<int> CTG_in_Labor_Room { get; set; }

    public Nullable<int> Curative_ { get; set; }

    public Nullable<int> Cureative { get; set; }

    public Nullable<int> Curitive_ { get; set; }

    public Nullable<int> Cystectomy { get; set; }

    public Nullable<int> Dailysis_Unit__Services { get; set; }

    public Nullable<int> Deliveries { get; set; }

    public Nullable<int> Delivery_Light_ { get; set; }

    public Nullable<int> Delivery_Table { get; set; }

    public Nullable<int> Delivery__Laboratory__Indoor__Outdoor { get; set; }

    public Nullable<int> Dengue_Test { get; set; }

    public Nullable<int> Dental_Care { get; set; }

    public Nullable<int> Dental_Department { get; set; }

    public Nullable<int> Dental_Imaging_System__DIS____Intraoral_Camera { get; set; }

    public Nullable<int> Dental_OPD { get; set; }

    public Nullable<int> DEntal_Public_Health_Facility { get; set; }

    public Nullable<int> Dental_Section { get; set; }

    public Nullable<int> Dental_unit { get; set; }

    public Nullable<int> Dental_X_Ray_Lab { get; set; }

    public Nullable<int> Dentel { get; set; }

    public Nullable<int> Dentestary { get; set; }

    public Nullable<int> Dermatology { get; set; }

    public Nullable<int> DHQ_Teaching_Hospital_Gujranwala { get; set; }

    public Nullable<int> Diabetic_Clinic { get; set; }

    public Nullable<int> Dia_Dynamic_Current__Physiotherapy_ { get; set; }

    public Nullable<int> Diagnostic_Facilities { get; set; }

    public Nullable<int> Diagnostic_Lab { get; set; }

    public Nullable<int> Diagnostic_Pathology_Laboratory { get; set; }

    public Nullable<int> Dialysis_Unit { get; set; }

    public Nullable<int> Dietary_Services { get; set; }

    public Nullable<int> District_Standing_Medical_Board { get; set; }

    public Nullable<int> Dog_Bite_Vaccination_Facility { get; set; }

    public Nullable<int> Doppler_Ultrasound { get; set; }

    public Nullable<int> E_C_G { get; set; }

    public Nullable<int> E_E_G { get; set; }

    public Nullable<int> E_M_G { get; set; }

    public Nullable<int> E_P_I { get; set; }

    public Nullable<int> E_T_T { get; set; }

    public Nullable<int> ECG { get; set; }

    public Nullable<int> ECG___X_Ray { get; set; }

    public Nullable<int> ECG__Cardiac_Test_ { get; set; }

    public Nullable<int> ECG___X_Ray___Lab { get; set; }

    public Nullable<int> ECG___X_Ray___Ultrasound { get; set; }

    public Nullable<int> ECG___X_Ray___Dental___Ultrasound { get; set; }

    public Nullable<int> ECG_Services { get; set; }

    public Nullable<int> Echo_Cardiography__Cardiac_Test_ { get; set; }

    public Nullable<int> Echocardiography { get; set; }

    public Nullable<int> ECO_CARDIOGRAPHY { get; set; }

    public Nullable<int> Ecocardiography { get; set; }

    public Nullable<int> ECT_Seaction { get; set; }

    public Nullable<int> Educational_Facility { get; set; }

    public Nullable<int> EGC { get; set; }

    public Nullable<int> Electric_Stimulator__Physiotherapy_ { get; set; }

    public Nullable<int> Electro_Medical_Equipment_Workshop { get; set; }

    public Nullable<int> ELECTRO_PHYSIOLOGY { get; set; }

    public Nullable<int> Electro_Retino_Gram_ERG__Eye_Test_ { get; set; }

    public Nullable<int> Electrophysiology { get; set; }

    public Nullable<int> Elise_Test { get; set; }

    public Nullable<int> Emergency_24_Hour { get; set; }

    public Nullable<int> Emergency_Operation_Theator { get; set; }

    public Nullable<int> Emergency_Services { get; set; }

    public Nullable<int> Emergency_Trauma_Center { get; set; }

    public Nullable<int> Emergency_Tray_ { get; set; }

    public Nullable<int> EMG_NCS { get; set; }

    public Nullable<int> EmONC_Services { get; set; }

    public Nullable<int> Endo_Post_Filling_ { get; set; }

    public Nullable<int> Endocrinology_ { get; set; }

    public Nullable<int> Endoscopy_Suite { get; set; }

    public Nullable<int> ENT_OPD { get; set; }

    public Nullable<int> ENT_Operation_Theater { get; set; }

    public Nullable<int> ENT_Specialist_Available { get; set; }

    public Nullable<int> EPI_Centre { get; set; }

    public Nullable<int> EPI_Vaccination_Department_ { get; set; }

    public Nullable<int> Epidemiologist_to_Govt_of_Punjab { get; set; }

    public Nullable<int> ERT_Radiotherapy__Cancer_Patients_ { get; set; }

    public Nullable<int> Esolation_Ward { get; set; }

    public Nullable<int> Essential_Drugs_Treatment { get; set; }

    public Nullable<int> Estradial_Test { get; set; }

    public Nullable<int> ETT_CCU { get; set; }

    public Nullable<int> Evening_OPD { get; set; }

    public Nullable<int> Exercise_Tolerance_Test__ETT_ { get; set; }

    public Nullable<int> EYE_OPD { get; set; }

    public Nullable<int> Eye_Operation_Theatre { get; set; }

    public Nullable<int> Eye_Specialist_Available { get; set; }

    public Nullable<int> Eye_Surgry { get; set; }

    public Nullable<int> Facio_Maxillary_Surgery { get; set; }

    public Nullable<int> Family_Planning_Services { get; set; }

    public Nullable<int> Farradic_Stimulation__Physiotherapy_ { get; set; }

    public Nullable<int> Female_Ward { get; set; }

    public Nullable<int> Ferritin_Test { get; set; }

    public Nullable<int> Fetal_Heart_Detector { get; set; }

    public Nullable<int> Fixed_appliance_upper_and_lower_ { get; set; }

    public Nullable<int> Fixed_Appliances_Upper_Or_Lower_ { get; set; }

    public Nullable<int> Floroscopy_Prodedure { get; set; }

    public Nullable<int> Fluoroscopy__Cardiac_Test_ { get; set; }

    public Nullable<int> FNA_Cytology_Tests { get; set; }

    public Nullable<int> FP_services { get; set; }

    public Nullable<int> Free_Diet_Patients { get; set; }

    public Nullable<int> FREE_RENAL_DIALYSIS { get; set; }

    public Nullable<int> FSH_Test { get; set; }

    public Nullable<int> Full_Denture_Upper_Or_Lower_ { get; set; }

    public Nullable<int> Fundus_Flurocum_Angiography__Eye_Test_ { get; set; }

    public Nullable<int> Gastroenterology_ { get; set; }

    public Nullable<int> Gastroscopy__Endoscopy_ { get; set; }

    public Nullable<int> General_OT { get; set; }

    public Nullable<int> General_Store { get; set; }

    public Nullable<int> General_Surgery_Instrument_Set { get; set; }

    public Nullable<int> Generators { get; set; }

    public Nullable<int> Genetics { get; set; }

    public Nullable<int> Genral__Wards { get; set; }

    public Nullable<int> Gingivactomy { get; set; }

    public Nullable<int> GLONOSCOPY { get; set; }

    public Nullable<int> Glucometer { get; set; }

    public Nullable<int> Glucose_Test { get; set; }

    public Nullable<int> Grid_Laser__Eye_Test_ { get; set; }

    public Nullable<int> Gym_Exercise_Machines__Physiotherapy_ { get; set; }

    public Nullable<int> Gynae___Obstetrics_OPD { get; set; }

    public Nullable<int> Gynae_Operation_Theatre { get; set; }

    public Nullable<int> Gynaecology { get; set; }

    public Nullable<int> Gyne___Obs_Facility_ { get; set; }

    public Nullable<int> Gyne_Ward__Male_General_Ward__Female_General_Ward { get; set; }

    public Nullable<int> Gynea { get; set; }

    public Nullable<int> Gynecology_Department { get; set; }

    public Nullable<int> H__Pylori__Chromatographic__Test { get; set; }

    public Nullable<int> H_I_V_Test { get; set; }

    public Nullable<int> Haemoglobin_Test { get; set; }

    public Nullable<int> Hakim { get; set; }

    public Nullable<int> HB_Test { get; set; }

    public Nullable<int> HBA1C_Test { get; set; }

    public Nullable<int> HBsAg_Test { get; set; }

    public Nullable<int> HCV_Genotyping_Test { get; set; }

    public Nullable<int> HCV_Test { get; set; }

    public Nullable<int> HDU { get; set; }

    public Nullable<int> Health_Care_Marketing { get; set; }

    public Nullable<int> health_education { get; set; }

    public Nullable<int> Hematology_Complete_Tests { get; set; }

    public Nullable<int> Hepatitis_A_E { get; set; }

    public Nullable<int> Hepatitis_B_C { get; set; }

    public Nullable<int> Hepatitis_Clinic { get; set; }

    public Nullable<int> Hepatitis_Control_Program { get; set; }

    public Nullable<int> Hepatitis_Profile { get; set; }

    public Nullable<int> Hepatology_ { get; set; }

    public Nullable<int> Hess_Test__Eye_Test_ { get; set; }

    public Nullable<int> Hikmat_OPD_Services { get; set; }

    public Nullable<int> Histopathology { get; set; }

    public Nullable<int> HIV { get; set; }

    public Nullable<int> Holter { get; set; }

    public Nullable<int> Homeopathic_Department { get; set; }

    public Nullable<int> Homeopathy { get; set; }

    public Nullable<int> Hot_Air_Oven { get; set; }

    public Nullable<int> ICU { get; set; }

    public Nullable<int> Immunization___Growth_Monitoring { get; set; }

    public Nullable<int> Incubator { get; set; }

    public Nullable<int> Indoor_Departments { get; set; }

    public Nullable<int> Indoor_Diagnostic___Treatment { get; set; }

    public Nullable<int> Indoor_Services { get; set; }

    public Nullable<int> Indoor_ward { get; set; }

    public Nullable<int> Infrared_Rays_Therpy__Physiotherapy_ { get; set; }

    public Nullable<int> Interior_Filling_ { get; set; }

    public Nullable<int> JAIDE_Diabetic_Clinic { get; set; }

    public Nullable<int> Lab__Pathalogical_ { get; set; }

    public Nullable<int> Lab___PCR { get; set; }

    public Nullable<int> Lab_Equipment { get; set; }

    public Nullable<int> Lab_Facility { get; set; }

    public Nullable<int> Lab_Investigation { get; set; }

    public Nullable<int> Lab_Services { get; set; }

    public Nullable<int> Lab_Test { get; set; }

    public Nullable<int> LAB__ULTRASOUND { get; set; }

    public Nullable<int> Lab__Equipment_ { get; set; }

    public Nullable<int> Laberotary { get; set; }

    public Nullable<int> Labor_Room { get; set; }

    public Nullable<int> Laboratory_Biochemical__ { get; set; }

    public Nullable<int> Laboratory_Hematology_ { get; set; }

    public Nullable<int> Laboratory_Histopathology_ { get; set; }

    public Nullable<int> Laboratory_Investigations { get; set; }

    public Nullable<int> Laboratory_Microbiology { get; set; }

    public Nullable<int> Laboratory_Services { get; set; }

    public Nullable<int> Labour_Room___clinical_labortary { get; set; }

    public Nullable<int> Laproscopy { get; set; }

    public Nullable<int> Laryngoscope { get; set; }

    public Nullable<int> Laundry_Services { get; set; }

    public Nullable<int> LFTs { get; set; }

    public Nullable<int> LH_Test { get; set; }

    public Nullable<int> Libortary { get; set; }

    public Nullable<int> Lipid_profile_Test { get; set; }

    public Nullable<int> Lithotripsy { get; set; }

    public Nullable<int> Liver_Clinic { get; set; }

    public Nullable<int> Low_Vision_Aids__Eye_Test_ { get; set; }

    public Nullable<int> M_P_Smear { get; set; }

    public Nullable<int> M_R_I { get; set; }

    public Nullable<int> Main_Operations_Theator { get; set; }

    public Nullable<int> Main_Pharmacy_Store___Satellite_Pharmacies { get; set; }

    public Nullable<int> Major___Minor_Operations { get; set; }

    public Nullable<int> Major_Operations_ { get; set; }

    public Nullable<int> Major_Surgery { get; set; }

    public Nullable<int> Malaria__Control_Program { get; set; }

    public Nullable<int> Mammography { get; set; }

    public Nullable<int> management_of_sick_child { get; set; }

    public Nullable<int> Maternal___Child_Health_Program { get; set; }

    public Nullable<int> Maternity_Services { get; set; }

    public Nullable<int> MCH_Facility { get; set; }

    public Nullable<int> Medical___Para_Medical_Staff { get; set; }

    public Nullable<int> Medical_Checkup___Treatment { get; set; }

    public Nullable<int> Medical_Fitness_Examination { get; set; }

    public Nullable<int> Medical_OPD { get; set; }

    public Nullable<int> Medicl_offers { get; set; }

    public Nullable<int> Microbiogical_test___Culture_and_sensitivity_testing { get; set; }

    public Nullable<int> Microbiology_Tests { get; set; }

    public Nullable<int> Microwave_Diathermy__Physiotherapy_ { get; set; }

    public Nullable<int> Mini_Lab_Services { get; set; }

    public Nullable<int> Minor_Operation_Theatre { get; set; }

    public Nullable<int> Minor_surgical_Operation { get; set; }

    public Nullable<int> MLC_Male___Female_24_Hour { get; set; }

    public Nullable<int> MLC_Postmartum { get; set; }

    public Nullable<int> MLCS_ { get; set; }

    public Nullable<int> MNCH_Services { get; set; }

    public Nullable<int> More_than_3_unit_Bridge_Porcelain__ { get; set; }

    public Nullable<int> Mortuary__Post_Mortem_Examination_Facility_ { get; set; }

    public Nullable<int> Mortuary_Management { get; set; }

    public Nullable<int> Mother__Child_Health { get; set; }

    public Nullable<int> MRI_All_Kinds { get; set; }

    public Nullable<int> Multiple_Rooted___Root_Canal_Therapy__ { get; set; }

    public Nullable<int> Nebulizar { get; set; }

    public Nullable<int> Neuro_Angiography { get; set; }

    public Nullable<int> Neurology_OPD { get; set; }

    public Nullable<int> Neurosciences_Nursing_Course { get; set; }

    public Nullable<int> Newborn_care { get; set; }

    public Nullable<int> NICU { get; set; }

    public Nullable<int> None { get; set; }

    public Nullable<int> Normal_Delivery { get; set; }

    public Nullable<int> NUCLEAR_CARDIOLOGY { get; set; }

    public Nullable<int> Nursary_ward { get; set; }

    public Nullable<int> Nursery__NNU_ { get; set; }

    public Nullable<int> nutritional_advice { get; set; }

    public Nullable<int> Obstetric_Instruments_Set { get; set; }

    public Nullable<int> Occult_Blood__Stool__Test { get; set; }

    public Nullable<int> OPD___Indoor { get; set; }

    public Nullable<int> OPERATION_THEATER_COMPLEX { get; set; }

    public Nullable<int> Operation_Theater_Facility_ { get; set; }

    public Nullable<int> OPERATION_THEATERS_FOR_CARDIAC_SURGERY { get; set; }

    public Nullable<int> Operaton_Theter { get; set; }

    public Nullable<int> OPG__Orthopentamogram_ { get; set; }

    public Nullable<int> OPG_DENTAL_X_RAY { get; set; }

    public Nullable<int> OPG_FOR_DENTAL { get; set; }

    public Nullable<int> Ophthalmic_Nursing_Course { get; set; }

    public Nullable<int> Opthalamic__Eye__Department { get; set; }

    public Nullable<int> Optical_Coherence_Tomography__Eye_Test_ { get; set; }

    public Nullable<int> Ortho_Operation_Theatre { get; set; }

    public Nullable<int> Orthopedic_OPD { get; set; }

    public Nullable<int> Orthoptic_Assessment__Corneal__Eye_Test_ { get; set; }

    public Nullable<int> OT_Ceilling_Light { get; set; }

    public Nullable<int> Outdoor_Diagnostic___Treatment { get; set; }

    public Nullable<int> Outdoor_Patient_Department { get; set; }

    public Nullable<int> Oxygen_Cylender { get; set; }

    public Nullable<int> Oxygen_Cylinder_with_Flow_Meters { get; set; }

    public Nullable<int> P_C_R { get; set; }

    public Nullable<int> Pacemaker_Implantation { get; set; }

    public Nullable<int> Paediatrics_OPD { get; set; }

    public Nullable<int> Pahtology_Support_to_patients_of_Ganga_Ram_Hospital_Lahore__ { get; set; }

    public Nullable<int> Pan_Retinal_Photocoagulation_PRP_Laser__Eye_Test_ { get; set; }

    public Nullable<int> Partial_Denture_1__5_Teeth__Artifical_Denture_ { get; set; }

    public Nullable<int> Partial_Denture_11__13_Teeth__Artifical_Denture_ { get; set; }

    public Nullable<int> Partial_Denture_6__10_Teeth__Artifical_Denture_ { get; set; }

    public Nullable<int> Pathology__Clinical_Lab_ { get; set; }

    public Nullable<int> Pathology_Lab_Services { get; set; }

    public Nullable<int> Patient_Welfare_Society { get; set; }

    public Nullable<int> PCR_HBV_Test { get; set; }

    public Nullable<int> PCR_HCV__QL__Test { get; set; }

    public Nullable<int> PCR_HCV__Real_Time__QN_Test { get; set; }

    public Nullable<int> PCR_TB_Test { get; set; }

    public Nullable<int> peads { get; set; }

    public Nullable<int> Pediatric_Nursing_Course { get; set; }

    public Nullable<int> Physical_Medicine___Rehabilitation { get; set; }

    public Nullable<int> Physical_Therapy_ { get; set; }

    public Nullable<int> Physio { get; set; }

    public Nullable<int> Physiotherapy_Services { get; set; }

    public Nullable<int> Physio_therapy_Unit { get; set; }

    public Nullable<int> Physiothrapy { get; set; }

    public Nullable<int> Pin_retained_Filling_ { get; set; }

    public Nullable<int> Plasma_Cell_Separation_Facility__Blood_Bank_ { get; set; }

    public Nullable<int> Porcelain_Crown_ { get; set; }

    public Nullable<int> POST_MORTEM_ { get; set; }

    public Nullable<int> Postmortem_ { get; set; }

    public Nullable<int> Pre_Natal__Natal___Post__Natal_Services { get; set; }

    public Nullable<int> Pregnency_Test { get; set; }

    public Nullable<int> Preventive_Paediatrics { get; set; }

    public Nullable<int> Progesteron_Test { get; set; }

    public Nullable<int> Prolactin_Test { get; set; }

    public Nullable<int> Pro_motive_ { get; set; }

    public Nullable<int> PSA_Test { get; set; }

    public Nullable<int> Psychiatric_Nursing_Course { get; set; }

    public Nullable<int> Psychiatry_OPD { get; set; }

    public Nullable<int> R_D__109_6R { get; set; }

    public Nullable<int> R_D__30_3R_Haroonabad { get; set; }

    public Nullable<int> R_D__71_4R_Haroonabad { get; set; }

    public Nullable<int> RADIOLOGY { get; set; }

    public Nullable<int> Reception__Information_Center { get; set; }

    public Nullable<int> Referral_to_RHC { get; set; }

    public Nullable<int> Refral { get; set; }

    public Nullable<int> Removable_Appliance_ { get; set; }

    public Nullable<int> Renal_Dialysis { get; set; }

    public Nullable<int> Renal_Transplantation { get; set; }

    public Nullable<int> Repair_of_Denture_ { get; set; }

    public Nullable<int> Review_of_Slides { get; set; }

    public Nullable<int> RFTs_Test { get; set; }

    public Nullable<int> RHC_Dajal { get; set; }

    public Nullable<int> Rheumatology_Clinic { get; set; }

    public Nullable<int> save_Delivery_Kit { get; set; }

    public Nullable<int> Scaling { get; set; }

    public Nullable<int> School_of_Nursing { get; set; }

    public Nullable<int> Serology_Tests { get; set; }

    public Nullable<int> Short_Wave_Diathermy__Physiotherapy_ { get; set; }

    public Nullable<int> Sigmidoscopy__Endoscopy_ { get; set; }

    public Nullable<int> Simple_extraction_of_one_Tooth_ { get; set; }

    public Nullable<int> Simple_Filling_ { get; set; }

    public Nullable<int> Single_Rooted___Root_Canal_Therphy__ { get; set; }

    public Nullable<int> SKIN_LASER { get; set; }

    public Nullable<int> Skin_OPD { get; set; }

    public Nullable<int> Social_Welfare_Services { get; set; }

    public Nullable<int> Specialized_Care { get; set; }

    public Nullable<int> SPECT_Myocardial_Perfusion_Scan { get; set; }

    public Nullable<int> Spirometery { get; set; }

    public Nullable<int> Sputum_Cytology_Tests { get; set; }

    public Nullable<int> Sputum_for_AFB { get; set; }

    public Nullable<int> Sucker_Machine { get; set; }

    public Nullable<int> Suger_Test { get; set; }

    public Nullable<int> Surgical_OPD { get; set; }

    public Nullable<int> Surgical_Operation_Theatres { get; set; }

    public Nullable<int> T_B_Dots { get; set; }

    public Nullable<int> T_B__Patients_Treatment_Facility { get; set; }

    public Nullable<int> T3_T4_TSH { get; set; }

    public Nullable<int> T3_Test { get; set; }

    public Nullable<int> T4_Test { get; set; }

    public Nullable<int> TB_Clinic { get; set; }

    public Nullable<int> TB_DOTS { get; set; }

    public Nullable<int> TB_Medicine { get; set; }

    public Nullable<int> TB_Treatment { get; set; }

    public Nullable<int> TB_dots_ { get; set; }

    public Nullable<int> TBO { get; set; }

    public Nullable<int> Testosterone_Test { get; set; }

    public Nullable<int> Thalessemia_Center { get; set; }

    public Nullable<int> Thalium { get; set; }

    public Nullable<int> TIBB_ { get; set; }

    public Nullable<int> Tibbi_Department { get; set; }

    public Nullable<int> TLC { get; set; }

    public Nullable<int> Topography__Eye_Test_ { get; set; }

    public Nullable<int> Torch_Profile { get; set; }

    public Nullable<int> Traction_Machine_Therapy__Physiotherapy_ { get; set; }

    public Nullable<int> Trauma_Center { get; set; }

    public Nullable<int> Treatment_of_baisc_ailments { get; set; }

    public Nullable<int> Treatment_of_fracture_Jaw_ { get; set; }

    public Nullable<int> treatment_on_common_ailment { get; set; }

    public Nullable<int> Trop_I__Chromatographic__Test { get; set; }

    public Nullable<int> Troponin { get; set; }

    public Nullable<int> Trop_T__Chromatographic__Test { get; set; }

    public Nullable<int> TSH_Test { get; set; }

    public Nullable<int> TWO_MODULAR_OPERATION_THEATERS { get; set; }

    public Nullable<int> U_S_G_ { get; set; }

    public Nullable<int> UCG { get; set; }

    public Nullable<int> Ultra_Sonographies { get; set; }

    public Nullable<int> Ultra_Sonography { get; set; }

    public Nullable<int> Ultrasography { get; set; }

    public Nullable<int> Ultrasonography__USG_ { get; set; }

    public Nullable<int> Ultrasound_All_Kinds { get; set; }

    public Nullable<int> Ultrasound_Doppler_ { get; set; }

    public Nullable<int> Ultrasound_Therapy__Physiotherapy_ { get; set; }

    public Nullable<int> ultrasound__ECG { get; set; }

    public Nullable<int> ULTRASOUNDS_including_DOPPLER_SCANNING { get; set; }

    public Nullable<int> Ultrasounography { get; set; }

    public Nullable<int> Undergraduate_Teaching { get; set; }

    public Nullable<int> Urea_Acid { get; set; }

    public Nullable<int> Urine_C_E { get; set; }

    public Nullable<int> Urine_Complete { get; set; }

    public Nullable<int> Urine_R_E { get; set; }

    public Nullable<int> Urine_Test { get; set; }

    public Nullable<int> Urology_OPD { get; set; }

    public Nullable<int> USG { get; set; }

    public Nullable<int> Vaccination { get; set; }

    public Nullable<int> Vector_Surveilance___Control_ { get; set; }

    public Nullable<int> Veneer_Metalic_Dowel_ { get; set; }

    public Nullable<int> Ventilators { get; set; }

    public Nullable<int> Vision__Refraction__Eye_Test_ { get; set; }

    public Nullable<int> Visual_Field__Eye_Test_ { get; set; }

    public Nullable<int> Widal_Test_diagnostic_tests__bacteriology_diagnostic_test_ { get; set; }

    public Nullable<int> X_Ray__Periapical__Occlusal__ { get; set; }

    public Nullable<int> X_RAY { get; set; }

    public Nullable<int> X_Ray_All_Kinds { get; set; }

    public Nullable<int> X_ray_and_ECG { get; set; }

    public Nullable<int> X_ray_Department { get; set; }

    public Nullable<int> X_RAY_Machine { get; set; }

    public Nullable<int> X_ray_OPg___Ceph_ { get; set; }

    public Nullable<int> X_ray_Periapical_ { get; set; }

    public Nullable<int> X_Ray_Unit { get; set; }

    public Nullable<int> X_Ray__ECG__Ultrasound { get; set; }

    public Nullable<int> X_Ray__ECG_Lab__Ultrasound { get; set; }

    public Nullable<int> Xray_ECG { get; set; }

    public Nullable<int> X_Rays { get; set; }

    public Nullable<int> Yag_Laser__Eye_Test_ { get; set; }

}

}
