
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_CurrentBalance
{

    public string EmployeeName { get; set; }

    public Nullable<int> HrId { get; set; }

    public Nullable<int> Month { get; set; }

    public decimal BAL { get; set; }

    public Nullable<int> Year { get; set; }

}

}
