
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_HF_test
{

    public string division { get; set; }

    public string district { get; set; }

    public string tehsil { get; set; }

    public string health_facility_name { get; set; }

    public string facility_type { get; set; }

    public int no_of_beds { get; set; }

    public int no_of_wards { get; set; }

    public Nullable<int> sanctioned { get; set; }

    public Nullable<int> working { get; set; }

    public Nullable<int> vacant { get; set; }

    public string contact_number { get; set; }

    public string email { get; set; }

    public string address { get; set; }

    public string facility_code { get; set; }

    public Nullable<double> latitude { get; set; }

    public Nullable<double> longitude { get; set; }

    public Nullable<int> facility_type_id { get; set; }

    public Nullable<int> district_id { get; set; }

    public string facility_id { get; set; }

}

}
