
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_Dashb_Roster
{

    public Nullable<int> SubDpt_ID { get; set; }

    public string SubDept_Name { get; set; }

    public string Morning { get; set; }

    public string Evening { get; set; }

    public string Night { get; set; }

    public string DayOffWeekend { get; set; }

    public string elevenEight { get; set; }

    public string OfficialTask { get; set; }

}

}
