
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_RosterDetail
{

    public int ID { get; set; }

    public Nullable<int> ProfileID { get; set; }

    public Nullable<int> SubDpt_ID { get; set; }

    public Nullable<int> Month { get; set; }

    public string RosterDate { get; set; }

    public string DayName { get; set; }

    public string EShift { get; set; }

    public string ShiftChange { get; set; }

    public Nullable<System.DateTime> DateFrom { get; set; }

    public Nullable<System.DateTime> DateTo { get; set; }

    public Nullable<int> IndRegId { get; set; }

    public Nullable<int> Shift_Id { get; set; }

    public string EmployeeName { get; set; }

    public string SubDept_Name { get; set; }

    public Nullable<int> Year { get; set; }

}

}
