
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_Rptattandance
{

    public int ID { get; set; }

    public Nullable<int> IndRegID { get; set; }

    public int HrId { get; set; }

    public string EmployeeName { get; set; }

    public string DName { get; set; }

    public Nullable<int> Designation_Id { get; set; }

    public string Designation_Name { get; set; }

    public Nullable<int> SubDept_Order { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<int> Month { get; set; }

    public string AttDate { get; set; }

    public Nullable<System.DateTime> LogDate { get; set; }

    public Nullable<int> SubDept_ID { get; set; }

    public string wd { get; set; }

    public int IsHOD { get; set; }

    public string Times { get; set; }

    public int Late { get; set; }

    public string LogStatus { get; set; }

}

}
