
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_New
{

    public Nullable<int> IndRegID { get; set; }

    public int ProfileID { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<int> Month { get; set; }

    public Nullable<int> TotalLate { get; set; }

    public Nullable<decimal> TotalAbsent { get; set; }

    public Nullable<decimal> TotalShort { get; set; }

    public Nullable<decimal> TotalSick { get; set; }

    public Nullable<decimal> TotalCasual { get; set; }

    public Nullable<decimal> TotalAvailedLate { get; set; }

    public Nullable<decimal> TotalLeaves { get; set; }

}

}
