
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_dpt_month_attendance
{

    public string EmployeeName { get; set; }

    public string Designation_Name { get; set; }

    public string AttDate { get; set; }

    public Nullable<System.DateTime> LogDate { get; set; }

    public string wd { get; set; }

    public string Times { get; set; }

    public int Late { get; set; }

    public string LogStatus { get; set; }

}

}
