
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_TotalLeaves
{

    public int ProfileId { get; set; }

    public string EmployeeName { get; set; }

    public string CNIC { get; set; }

    public string Designation_Name { get; set; }

    public Nullable<decimal> TotalSL { get; set; }

    public Nullable<decimal> TotalSick { get; set; }

    public Nullable<decimal> TotalCasual { get; set; }

    public Nullable<decimal> TotalLev { get; set; }

    public Nullable<decimal> Bal { get; set; }

    public string WorkingHFMISCode { get; set; }

    public string HfmisCode { get; set; }

}

}
