
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_all_activity_log
{

    public Nullable<long> ROWNUM { get; set; }

    public Nullable<int> Level_Id { get; set; }

    public string HfmisCode { get; set; }

    public long Id { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Param1 { get; set; }

    public string Param2 { get; set; }

    public string nlog { get; set; }

}

}
