
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_ProjectsDetail
{

    public Nullable<int> Sr { get; set; }

    public int Project_ID { get; set; }

    public string Project_Name { get; set; }

    public string Project_Description { get; set; }

    public Nullable<int> Team_ID { get; set; }

    public Nullable<int> Project_TypeID { get; set; }

    public Nullable<int> SubDept_ID { get; set; }

    public string SubDept_Name { get; set; }

    public string Implementation_Detail { get; set; }

    public Nullable<int> Current_Status_ID { get; set; }

    public Nullable<int> Frequency_Data_ID { get; set; }

    public string URL { get; set; }

    public string Project_Type { get; set; }

    public string Team_Name { get; set; }

    public string Current_Status { get; set; }

    public string Frequency_Data { get; set; }

}

}
