
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_AttendanceCalc
{

    public Nullable<int> IndRegID { get; set; }

    public int ProfileID { get; set; }

    public Nullable<System.DateTime> DateOnlyRecord { get; set; }

    public string LogStatus { get; set; }

    public Nullable<System.DateTime> DateTimeRecord { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<int> Month { get; set; }

    public Nullable<int> TotalLateDay { get; set; }

    public Nullable<decimal> AbsentCount { get; set; }

    public decimal TotalShort { get; set; }

    public decimal TotalSick { get; set; }

    public decimal TotalCasual { get; set; }

    public Nullable<decimal> AvailedLate { get; set; }

}

}
