
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class View_TeamMembers
{

    public int TeamM_ID { get; set; }

    public Nullable<int> Team_ID { get; set; }

    public Nullable<int> ProfileID { get; set; }

    public Nullable<int> Is_Active { get; set; }

    public Nullable<int> Is_Lead { get; set; }

    public string Entered_By { get; set; }

    public Nullable<System.DateTime> Entered_DateTime { get; set; }

    public string EmployeeName { get; set; }

    public string StatusName { get; set; }

    public string Team_Name { get; set; }

}

}
