
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VP
{

    public int Id { get; set; }

    public string HFMIS_Code { get; set; }

    public int HF_Id { get; set; }

    public int VPType { get; set; }

    public Nullable<int> Department_Id { get; set; }

    public int PostType_Id { get; set; }

    public int Designation_Id { get; set; }

    public int EmpMode_Id { get; set; }



    public virtual HealthFacility HealthFacility { get; set; }

    public virtual HrDepartment HrDepartment { get; set; }

    public virtual HrDesignation HrDesignation { get; set; }

    public virtual HrEmpMode HrEmpMode { get; set; }

    public virtual HrPost_Type HrPost_Type { get; set; }

}

}
