
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VPHolderView
{

    public int Id { get; set; }

    public Nullable<int> TotalSeats { get; set; }

    public Nullable<int> TotalSeatsVacant { get; set; }

    public Nullable<int> TotalSeatsHold { get; set; }

    public Nullable<long> VpMaster_Id { get; set; }

    public Nullable<long> VpDetail_Id { get; set; }

    public string FileNumber { get; set; }

    public Nullable<int> TrackingNumber { get; set; }

    public string EmployeeName { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<int> Application_Id { get; set; }

    public string ESR { get; set; }

    public string ELR { get; set; }

    public string OrderNumber { get; set; }

    public Nullable<int> OrderAttachment_Id { get; set; }

    public Nullable<long> Elc_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string CreatedBy { get; set; }

    public string User_Id { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public int TotalSanctioned { get; set; }

    public Nullable<int> TotalWorking { get; set; }

    public int Profiles { get; set; }

    public int WorkingProfiles { get; set; }

    public Nullable<int> Vacant { get; set; }

    public string HFMISCode { get; set; }

    public int HF_Id { get; set; }

    public string DivisionCode { get; set; }

    public string DivisionName { get; set; }

    public string DistrictCode { get; set; }

    public string DistrictName { get; set; }

    public string TehsilCode { get; set; }

    public string TehsilName { get; set; }

    public string HFName { get; set; }

    public int PostType_Id { get; set; }

    public string PostTypeName { get; set; }

    public int Desg_Id { get; set; }

    public string DsgName { get; set; }

    public Nullable<int> BPSWorking { get; set; }

    public Nullable<int> Cadre_Id { get; set; }

    public string CadreName { get; set; }

    public Nullable<int> BPS { get; set; }

    public Nullable<int> BPS2 { get; set; }

    public Nullable<int> HFTypeId { get; set; }

    public string HFTypeCode { get; set; }

    public string HFTypeName { get; set; }

    public Nullable<long> EntityLifeCycle_IdM { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Last_Modified_By { get; set; }

    public string Modified_By { get; set; }

    public Nullable<System.DateTime> Modified_Date { get; set; }

    public string Users_Id { get; set; }

    public Nullable<int> ActingCharge { get; set; }

    public Nullable<int> ActiveCharge { get; set; }

    public Nullable<int> Adhoc { get; set; }

    public Nullable<int> Adjusted { get; set; }

    public Nullable<int> AdjustedForPayPurpose { get; set; }

    public Nullable<int> Contract { get; set; }

    public Nullable<int> CurrentCharge { get; set; }

    public Nullable<int> DailyWages { get; set; }

    public Nullable<int> Deputation { get; set; }

    public Nullable<int> GeneralDuty { get; set; }

    public Nullable<int> OnPayScale { get; set; }

    public Nullable<int> ProjectContract { get; set; }

    public Nullable<int> Regular { get; set; }

    public Nullable<int> Reinstated { get; set; }

    public Nullable<int> PHFMC { get; set; }

    public Nullable<int> Consultancy { get; set; }

}

}
