
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VPMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VPMaster()
    {

        this.ApplicationMasters = new HashSet<ApplicationMaster>();

        this.VPDetails = new HashSet<VPDetail>();

        this.VPHolders = new HashSet<VPHolder>();

        this.VPProfiles = new HashSet<VPProfile>();

    }


    public long Id { get; set; }

    public int HF_Id { get; set; }

    public string HFMISCode { get; set; }

    public int Desg_Id { get; set; }

    public int PostType_Id { get; set; }

    public int TotalSanctioned { get; set; }

    public Nullable<int> TotalWorking { get; set; }

    public Nullable<int> TotalApprovals { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public Nullable<int> BPSWorking { get; set; }

    public Nullable<bool> Locked { get; set; }

    public int TotalSanctionedPHFMC { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApplicationMaster> ApplicationMasters { get; set; }

    public virtual Entity_Lifecycle Entity_Lifecycle { get; set; }

    public virtual HealthFacility HealthFacility { get; set; }

    public virtual HrDesignation HrDesignation { get; set; }

    public virtual HrPost_Type HrPost_Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VPDetail> VPDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VPHolder> VPHolders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VPProfile> VPProfiles { get; set; }

}

}
