
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VpMasterLog
{

    public long Id { get; set; }

    public Nullable<long> VpMaster_Id { get; set; }

    public Nullable<int> Action_Id { get; set; }

    public Nullable<int> SanctionedBefore { get; set; }

    public Nullable<int> SanctionedAfter { get; set; }

    public Nullable<int> FilledBefore { get; set; }

    public Nullable<int> FilledAfter { get; set; }

    public string CreatedBy { get; set; }

    public string User_Id { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string Remarks { get; set; }

}

}
