
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VpMDView
{

    public long Id { get; set; }

    public Nullable<int> HFId { get; set; }

    public string DivisionCode { get; set; }

    public string DivisionName { get; set; }

    public string DistrictCode { get; set; }

    public string DistrictName { get; set; }

    public string TehsilCode { get; set; }

    public string TehsilName { get; set; }

    public string FullName { get; set; }

    public int PostType_Id { get; set; }

    public string PostTypeName { get; set; }

    public int Desg_Id { get; set; }

    public string DsgName { get; set; }

    public Nullable<int> Scale { get; set; }

    public Nullable<int> HFTypeId { get; set; }

    public string HFTypeCode { get; set; }

    public string HFTypeName { get; set; }

    public string HFName { get; set; }

    public string HFMISCode { get; set; }

    public int TotalSanctioned { get; set; }

    public int TotalWorking { get; set; }

    public Nullable<int> Vacant { get; set; }

    public Nullable<int> Regular { get; set; }

    public Nullable<int> Contract { get; set; }

    public Nullable<int> Adhoc { get; set; }

    public string CadreName { get; set; }

}

}
