
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VPostDtl
{

    public int Id { get; set; }

    public int Scale_Id { get; set; }

    public Nullable<int> EmpMode_Id { get; set; }

    public Nullable<int> Working { get; set; }



    public virtual HrEmpMode HrEmpMode { get; set; }

    public virtual HrScale HrScale { get; set; }

    public virtual VPostMast VPostMast { get; set; }

}

}
