
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VPProfileView
{

    public int Id { get; set; }

    public Nullable<long> VPMaster_Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public string EmployeeName { get; set; }

    public string FatherName { get; set; }

    public string CNIC { get; set; }

    public string WDesignation_Name { get; set; }

    public string Designation_Name { get; set; }

    public Nullable<int> CurrentGradeBPS { get; set; }

    public string EmpMode_Name { get; set; }

    public string StatusName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Cadre_Name { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string Users_Id { get; set; }

}

}
