
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VPProfile
{

    public int Id { get; set; }

    public Nullable<long> VPMaster_Id { get; set; }

    public Nullable<int> Profile_Id { get; set; }

    public Nullable<long> EntityLifecycle_Id { get; set; }



    public virtual VPMaster VPMaster { get; set; }

}

}
