
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class VpSpecialized
{

    public int Id { get; set; }

    public string Designation { get; set; }

    public string HF { get; set; }

    public string District { get; set; }

    public Nullable<int> Sanctioned { get; set; }

    public Nullable<int> Filled { get; set; }

    public Nullable<int> Vacant { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
