
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hrmis.Models.DbModel
{

using System;
    using System.Collections.Generic;
    
public partial class WMO_Grievances
{

    public int Id { get; set; }

    public Nullable<int> Merit_Id { get; set; }

    public string HFMISCode { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

}

}
